---
sidebar: sidebar 
permalink: qsg.html 
keywords: QSG, ONTAP tools for VMware vSphere, Quick start guide, Installing 
summary: VMware vSphere용 ONTAP 툴을 구축하고 초기화하는 방법에 대한 지침은 에 나와 있습니다. 
---
= VMware vSphere용 ONTAP 툴 빠른 시작
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
VMware vSphere용 ONTAP 툴은 ONTAP 툴, VASA Provider 및 SRA(Storage Replication Adapter) 확장을 포함한 단일 vCenter Server 플러그인입니다. ONTAP 툴은 ESXi 호스트 설정을 구성하고 모범 사례를 사용하여 ONTAP 스토리지를 프로비저닝하므로 모든 ONTAP vSphere 환경에 권장됩니다. VASA Provider는 가상 볼륨(VVol) 지원에 필요하며 SRA는 VMware Site Recovery Manager와 함께 작동합니다.



== 설치 준비 중

플러그인을 가상 어플라이언스로 구축하면 각 제품을 vCenter Server에 별도로 설치 및 등록하는 수고를 줄일 수 있습니다.



=== 구현할 수 있습니다

ONTAP 툴은 VMware vCenter Server vCSA(Virtual Appliance)와 함께 사용할 수 있습니다. ESXi 시스템이 포함된 지원되는 vSphere에 ONTAP 툴을 구축해야 합니다.

최소 공간 및 호스트 사이징 요구사항은 다음과 같습니다.

[cols="25,75"]
|===
| * 시스템 * | * 최소 요구 사항 * 


| 공간 | 씬 프로비저닝 설치의 경우 2.1GB, 씩 프로비저닝 설치의 경우 54.0GB 


| 호스트 사이징 | 권장 메모리: 12GB, 권장 CPU: 2 
|===
다음 라이센스를 알고 있어야 합니다.

[cols="25,75"]
|===
| * 라이센스 * | * 설명 * 


| SnapMirror를 참조하십시오 | (선택 사항) VVOL 복제를 사용하는 경우 SRA 및 VASA Provider의 페일오버 작업을 수행하는 데 필요합니다. 


| 플랙스클론 | (선택 사항) SRA 및 VASA Provider의 VVol 운영을 위한 테스트 페일오버 작업을 수행하는 데 필요합니다. 
|===
ONTAP 도구는 다음과 같은 기본 양방향 TCP 포트를 사용합니다.

|===


| * 추가 요구 사항 * | * 설명 열 * 


 a| 
9083
 a| 
VASA Provider와 SRA(Storage Replication Adapter)가 모두 활성화되면 이 포트를 사용하여 vCenter Server와 통신합니다. 이 포트는 TCP/IP 설정을 얻는 데도 필요합니다. 이 포트는 VP 지원 번들을 다운로드하고, Web-CLI 사용자 인터페이스를 액세스하고, VMware에서 VP로 경로 통신을 제어하는 데 사용됩니다.



 a| 
443
 a| 
자격 증명을 구성한 방법에 따라 VMware vCenter Server와 스토리지 시스템은 이 포트에서 보안 통신을 수신합니다. 이 포트는 클라이언트-서버 통신 아키텍처에서 사용됩니다. 443 포트는 보안 연결에 대해 기본적으로 설정됩니다. 클라이언트는 REST API를 사용하는 모든 자동화 클라이언트일 수 있으며, 서버에 대한 연결을 시작하고, 엔드포인트는 데이터를 교환합니다.



 a| 
8143
 a| 
ONTAP 도구는 이 포트에서 보안 통신을 수신합니다. 이 포트는 클라이언트-서버 통신 아키텍처에서 사용됩니다. 클라이언트는 REST API를 사용하는 모든 자동화 클라이언트일 수 있으며, 서버에 대한 연결을 시작하고, 엔드포인트는 데이터를 교환합니다. 이 포트는 ONTAP 도구 서비스 및 ONTAP 도구 서버 로그를 내보내는 데 사용됩니다. register.html 페이지는 이 포트에서 호스팅됩니다. 나머지 Swagger가 이 포트에 노출되었습니다.



 a| 
8443
 a| 
이 포트는 원격 플러그인 서비스에 사용됩니다.

|===
최소 스토리지 및 애플리케이션 요구사항:

|===
| * 스토리지, 호스트 및 애플리케이션 * | * 버전 요구 사항 * 


| ONTAP | ONTAP 9.7, 9.8P1 이상 


| VMware vSphere, vCenter Server, ESXi 호스트, SRM(Site Recovery Manager), 플러그인 애플리케이션 및 데이터베이스 열 1 | 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["상호 운용성 매트릭스 툴"^] 
|===


=== ONTAP 툴 요구사항

* vCenter Server 환경을 구성하고 설정합니다.
* ova 파일을 다운로드합니다.
* vCenter Server 인스턴스에 대한 로그인 자격 증명입니다.
* ONTAP 도구를 배포하는 동안 브라우저 캐시 문제가 발생하지 않도록 브라우저 캐시를 삭제합니다.
* 가상 어플라이언스가 ICMP 핑에 응답하도록 기본 게이트웨이를 구성합니다.
* 가상 어플라이언스에 대한 유효한 DNS 호스트 이름입니다.




=== SRA에 대한 선택적 요구 사항

VMware Site Recovery Manager와 함께 사용하기 위해 가상 어플라이언스를 구축하는 경우 다음을 설치해야 합니다. * 를 다운로드했습니다 `.tar.gz` SRM 어플라이언스를 사용하는 경우 SRA용 파일입니다.



== ONTAP 도구 배포

.단계
. 다운로드 `.zip` 에서 받은 바이너리와 서명된 인증서가 포함된 파일입니다 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support 사이트"^] ONTAP 툴을 구축하는 vSphere 클라이언트 시스템으로
. 의 압축을 풉니다 `.zip` 파일을 만들고 를 배포합니다 `.ova` 파일.
+
SRA를 배포하는 경우 소스 사이트와 대상 사이트 모두에 '.ova' 파일을 배포해야 합니다.

. vSphere Web Client에 로그인하고 * Home * > * Host and Clusters * 를 선택합니다.
. 필요한 데이터 센터를 마우스 오른쪽 단추로 클릭한 다음 * Deploy OVF template * 을 클릭합니다.
+
vCenter7.0u3e 및 이후 릴리스를 사용하는 경우 다음 작업을 수행하고 그렇지 않은 경우 5단계를 진행합니다. OVA 바이너리 무결성이 훼손되지 않았는지 확인하는 선택적 단계입니다.

+
** NetApp Support 사이트에서 _OTV_INTER_ROOT_CERT_CH체인.PEM_파일을 다운로드합니다.
** vCenter * > * administration * > * certificate management * 로 이동합니다.
** Add trusted root certificate * 옵션을 클릭합니다.
** 찾아보기 * 를 클릭하고 _OTV_INTER_ROOT_CERT_CH체인.pem_파일 경로를 입력합니다.
** 추가 * 를 클릭합니다.
+

NOTE: Entrust Code Signing - OVCS2(신뢰할 수 있는 인증서) 메시지는 다운로드한 OVA 파일의 무결성을 확인합니다. Entrust Code Signing - OVCS2 (Invalid certificate) 메시지가 표시되면 VMware vCenter Server를 7.0U3E 이상 버전으로 업그레이드합니다.



. ova 파일의 URL을 입력하거나 .ova 파일이 저장된 폴더를 찾은 후 * 다음 * 을 클릭합니다.
. 필수 세부 정보를 입력하여 구축을 완료합니다.



NOTE: (선택 사항) vCenter Server에 등록하지 않고 컨테이너를 생성하려면 vCenter 구성 또는 VCF 활성화 섹션에서 VCF(VMware Cloud Foundation) 활성화 확인란을 선택합니다.

작업 * 탭에서 배포 진행 상황을 보고 배포가 완료될 때까지 기다릴 수 있습니다.

구축 체크섬 검증의 일부로 수행됩니다. 배포에 실패하면 다음을 수행합니다.

. vpserver/logs/checksum.log를 확인합니다. "checksum verification failed(체크섬 확인 실패)"라고 표시되면 실패한 jar의 확인을 동일한 로그에서 볼 수 있습니다.
+
로그 파일에는 _sha256sum -c/opt/netapp/vpserver/conf/checksum_ 실행이 포함되어 있습니다.

. vscserver/log/checksum.log를 확인합니다. "checksum verification failed(체크섬 확인 실패)"라고 표시되면 실패한 jar의 확인을 동일한 로그에서 볼 수 있습니다.
+
로그 파일에는 _sha256sum -c/opt/NetApp/vscerver/etc/checksum_ 실행이 포함되어 있습니다.





=== SRM에 SRA 배포

SRA는 Windows SRM 서버 또는 8.2 SRM 어플라이언스에 배포할 수 있습니다.



==== SRM 어플라이언스에서 SRA 업로드 및 구성

.단계
. 에서 '.tar.gz' 파일을 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support 사이트"^].
. SRM 어플라이언스 화면에서 * 스토리지 복제 어댑터 * > * 새 어댑터 * 를 클릭합니다.
. SRM에 .tar.gz 파일을 업로드합니다.
. 어댑터를 다시 검색하여 SRM 스토리지 복제 어댑터 페이지에서 세부 정보가 업데이트되었는지 확인합니다.
. putty를 사용하여 SRM 어플라이언스에 관리자 계정을 사용하여 로그인합니다.
. 루트 사용자로 전환합니다: 'u root'
. 로그 위치에 명령을 입력하여 SRA Docker에서 사용하는 Docker ID를 docker ps -l로 가져옵니다
. 컨테이너 ID: docker exec -it -u SRM <컨테이너 ID>sh'에 로그인합니다
. ONTAP 도구 IP 주소 및 암호를 사용하여 SRM 구성: `perl command.pl -I <otv-IP> administrator <otv-password>`스토리지 자격 증명이 저장되었음을 확인하는 성공 메시지가 표시됩니다.




==== SRA 자격 증명 업데이트

.단계
. 다음을 사용하여 /SRM/SRA/conf 디렉토리의 내용을 삭제합니다.
+
.. 'cd/srm/srs/conf'
.. rm-rf *


. perl 명령을 실행하여 새 자격 증명으로 SRA를 구성합니다.
+
.. "CD/SRM/SRA/"
.. `perl command.pl -I <otv-IP> administrator <otv-password>`






==== VASA Provider 및 SRA를 사용하도록 설정합니다

.단계
. OVA ONTAP 툴 구축 중에 제공된 vCenter IP를 사용하여 vSphere 웹 클라이언트에 로그인합니다.
. 바로 가기 페이지에서 플러그인 섹션에서 * NetApp ONTAP tools * 를 클릭합니다.
. ONTAP 도구 왼쪽 창에서 * 설정 > 관리 설정 > 기능 관리 * 를 선택하고 필요한 기능을 활성화합니다.
+

NOTE: VASA Provider는 기본적으로 설정되어 있습니다. VVOL 데이터 저장소의 복제 기능을 사용하려면 VVol 복제 활성화 전환 버튼을 사용합니다.

. ONTAP 도구의 IP 주소와 관리자 암호를 입력한 다음 * 적용 * 을 클릭합니다.

