---
permalink: deploy/concept_installation_workflow_for_existing_users_of_ontap_tools.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴의 9.x 릴리즈는 최신 버전으로 현재 위치 업그레이드를 지원합니다. 
---
= 기존 ONTAP 도구 사용자를 위한 배포 워크플로
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴의 9.x 릴리즈는 최신 버전으로 현재 위치 업그레이드를 지원합니다.

Virtual Storage Console 6.x, Storage Replication Adapter 2.x, 3.x, 4.x 및 VASA Provider 6.x와 같은 개별 애플리케이션의 이전 릴리즈에서는 다른 업그레이드 프로세스를 사용합니다. 구축 과정에서 이러한 기존 버전의 VSC 또는 VASA Provider 또는 SRA가 설치되어 있는 경우 다음 작업을 수행해야 합니다.

. ONTAP 툴의 최신 릴리즈 배포
. 기존 구성 데이터를 마이그레이션합니다.
+
구성 데이터에는 스토리지 시스템 자격 증명과 "kaminoprefs.xml" 및 "vscPreferences.xml" 파일에 있는 기본 설정이 포함됩니다.



link:../configure/reference_set_ipv4_or_ipv6.html["기본 설정 파일을 사용하여 IPv4 또는 IPv6를 설정합니다"]

대부분의 경우 구성 데이터를 마이그레이션할 필요가 없을 수 있습니다. 그러나 이전에 기본 설정 파일을 사용자 지정한 경우에는 기본 설정 파일을 검토하고 새로 배포된 ONTAP 도구와 유사한 변경 작업을 수행할 수 있습니다. 다음 중 하나를 수행할 수 있습니다.

* 사용 https://mysupport.netapp.com/tools/index.html["SnapCenter 및 가상 스토리지 콘솔용 NetApp 임포트 유틸리티"] 스토리지 시스템 자격 증명을 VSC 6.X 및 SRA 4.X에서 새 배포로 마이그레이션합니다.
* 스토리지 시스템을 새로 구축된 ONTAP 툴에 추가하고 추가할 때 자격 증명을 지정합니다.


VASA Provider 6.X에서 업그레이드하는 경우 업그레이드하기 전에 VASA Provider를 등록 취소해야 합니다. 자세한 내용은 현재 릴리즈의 설명서를 참조하십시오.

SRA 4.0 이전 버전에서도 업그레이드하는 경우:

* SRA 4.0P1을 사용하는 경우 먼저 SRA9.6으로 업그레이드한 다음 SRA 9.6 릴리스의 현재 위치 업그레이드를 수행해야 합니다. 나중에 ONTAP 도구의 최신 릴리즈로 업그레이드할 수 있습니다.
+
link:../deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html["ONTAP 툴의 최신 릴리즈로 업그레이드하십시오"]

* SRA 2.1 또는 3.0을 사용하는 경우 먼저 기존 사이트 구성 세부 정보를 기록해야 합니다.
+
_ONTAP_용 스토리지 복제 어댑터 4.0에 대한 설치 및 설정 안내서는 "업그레이드 개요" 섹션에 자세히 설명되어 있습니다. 이러한 SRA 릴리즈에서는 VASA Provider도 사용하므로 VASA Provider를 등록 취소한 다음 최신 버전의 ONTAP 툴을 배포해야 합니다. 업그레이드가 완료되면 서버의 이전 버전(.ova)을 제거할 수 있습니다.



모든 SRA 업그레이드의 경우 SRA 소프트웨어(".msi" 파일에 의해 설치되는 Site Recovery Manager 서버의 어댑터)를 Site Recovery Manager 서버에서 제거해야 합니다. Windows 시스템 제어판을 사용하여 소프트웨어를 제거한 다음, '.msi' 파일을 사용하여 SRA 서버에 최신 SRA 소프트웨어를 설치할 수 있습니다.

VASA Provider를 구축한 경우 기존 설정에서 업그레이드한 후 '설정 편집' 옵션을 사용하여 ONTAP 도구의 메모리 크기를 12GB로 구성해야 합니다. 또한 가상 메모리 예약을 수정해야 합니다. 메모리 크기를 수정하려면 가상 머신의 전원을 꺼야 합니다.

VSC, VASA Provider, SRA를 위한 가상 어플라이언스 7.2 또는 7.2.1 릴리즈를 사용하는 경우 유니파이드 어플라이언스의 9.7P1 이상 릴리즈로 직접 업그레이드할 수 없습니다. 먼저 기존 설정을 가상 어플라이언스의 9.7 릴리즈로 업그레이드한 다음 최신 릴리즈로 업그레이드해야 합니다.

ONTAP 도구 9.10으로 업그레이드하려면 가상 어플라이언스 9.7P1 이상을 실행해야 합니다. 가상 어플라이언스의 9.7P1 이전 버전에서 업그레이드할 수 없습니다.

최신 버전의 ONTAP 도구를 배포하려는 경우 "ONTAP 도구 배포에 대한 요구 사항" 항목을 참조하십시오 'ONTAP 도구의 최신 버전으로 업그레이드' 항목에는 현재 위치 업그레이드를 수행하는 방법에 대한 정보가 들어 있습니다.

* 관련 정보 *

https://mysupport.netapp.com/site/tools[]
