---
permalink: deploy/reference_port_requirements_for_vsc.html 
sidebar: sidebar 
keywords: port requirements 
summary: 기본적으로 ONTAP 툴은 지정된 포트를 사용하여 스토리지 시스템과 VMware vCenter Server를 포함한 구성 요소 간의 통신을 지원합니다. 방화벽이 활성화되어 있는 경우, 방화벽을 예외 허용으로 설정해야 합니다. 
---
= ONTAP 도구에 대한 포트 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 ONTAP 툴은 지정된 포트를 사용하여 스토리지 시스템과 VMware vCenter Server를 포함한 구성 요소 간의 통신을 지원합니다. 방화벽이 활성화되어 있는 경우, 방화벽을 예외 허용으로 설정해야 합니다.

Windows 이외의 방화벽의 경우 ONTAP 도구가 사용하는 특정 포트에 대한 액세스를 수동으로 부여해야 합니다. 이러한 포트에 대한 액세스 권한을 부여하지 않으면 다음과 같은 오류 메시지가 표시됩니다.

서버와 통신할 수 없습니다

ONTAP 도구는 다음과 같은 기본 양방향 TCP 포트를 사용합니다.

|===


| * 기본 포트 번호 * | * 설명 * 


 a| 
9083
 a| 
VASA Provider와 SRA(Storage Replication Adapter)가 모두 활성화되면 이 포트를 사용하여 vCenter Server와 통신합니다. 이 포트는 TCP/IP 설정을 얻는 데도 필요합니다. 이 포트는 VP 지원 번들을 다운로드하고, Web-CLI 사용자 인터페이스를 액세스하고, VMware에서 VP로 경로 통신을 제어하는 데 사용됩니다.



 a| 
443
 a| 
자격 증명을 구성한 방법에 따라 VMware vCenter Server와 스토리지 시스템은 이 포트에서 보안 통신을 수신합니다. 이 포트는 클라이언트-서버 통신 아키텍처에서 사용됩니다. 443 포트는 보안 연결에 대해 기본적으로 설정됩니다. 클라이언트는 REST API를 사용하는 모든 자동화 클라이언트일 수 있으며, 서버에 대한 연결을 시작하고, 엔드포인트는 데이터를 교환합니다.



 a| 
8143
 a| 
ONTAP 도구는 이 포트에서 보안 통신을 수신합니다. 이 포트는 클라이언트-서버 통신 아키텍처에서 사용됩니다. 클라이언트는 REST API를 사용하는 모든 자동화 클라이언트일 수 있으며, 서버에 대한 연결을 시작하고, 엔드포인트는 데이터를 교환합니다. 이 포트는 ONTAP 도구 서비스 및 ONTAP 도구 서버 로그를 내보내는 데 사용됩니다. register.html 페이지는 이 포트에서 호스팅됩니다. 나머지 Swagger가 이 포트에 노출되었습니다.



 a| 
8443
 a| 
이 포트는 원격 플러그인 서비스에 사용됩니다.



 a| 
7
 a| 
ONTAP 도구는 ONTAP에 반향 요청을 전송하여 도달 여부를 확인하며, 스토리지를 추가할 때만 필요합니다
나중에 비활성화할 수 있습니다.

|===

NOTE: ONTAP 도구를 배포하기 전에 ICMP(인터넷 제어 메시지 프로토콜)를 활성화해야 합니다.

ICMP가 비활성화되어 있으면 ONTAP 툴의 초기 구성이 실패하고 구축 후 ONTAP 툴이 ONTAP 툴 및 VASA Provider 서비스를 시작할 수 없습니다. 구축 후에는 ONTAP 툴 및 VASA Provider 서비스를 수동으로 설정해야 합니다.
