---
permalink: deploy/reference_configure_storage_replication_adapter_for_highly_scaled_environment.html 
sidebar: sidebar 
keywords:  
summary: 'SRA(Storage Replication Adapter)\ 에 권장되는 설정에 따라 저장소 시간 초과 간격을 구성하여 고도로 확장된 환경에서 최적의 성능을 발휘해야 합니다.' 
---
= 확장성이 높은 환경에 맞게 스토리지 복제 어댑터를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SRA(Storage Replication Adapter)에 권장되는 설정에 따라 스토리지 시간 초과 간격을 구성하여 고도로 확장된 환경에서 최적의 성능을 발휘하도록 해야 합니다.



== 저장소 공급자 설정

확장 환경의 경우 SRM에서 다음 시간 초과 값을 설정해야 합니다.

|===


| 고급 설정 | 시간 초과 값 


 a| 
StorageProvider.재서명시간 초과
 a| 
설정 값을 900초에서 12000초로 늘립니다.



 a| 
storageProvider.hostRescandDelaySec을 참조하십시오
 a| 
60



 a| 
storageProvider.hostRescanRepeatCnt 를 참조하십시오
 a| 
20



 a| 
storageProvider.hostRescanTimeoutSec을 참조하십시오
 a| 
높은 값 설정(예: 99999)

|===
StorageProvider.autoResignatureMode 옵션도 활성화해야 합니다.

스토리지 공급자 설정 수정에 대한 자세한 내용은 VMware 설명서를 참조하십시오.

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html["VMware vSphere 설명서: 스토리지 공급자 설정 변경"]



== 저장소 설정

크기가 큰 환경의 경우 storage.commandTimeout 및 storage.maxConcurrentCommandCnt 시간 제한 간격을 99,999초로 설정해야 합니다.


NOTE: 지정된 시간 제한 간격이 최대값입니다. 최대 시간 초과에 도달할 때까지 기다릴 필요가 없습니다. 대부분의 명령이 설정된 최대 시간 제한 간격 내에 완료됩니다.

또한 SRA가 vvol.properties 파일에서 단일 작업을 수행하는 최대 시간을 설정해야 합니다. offtap.operation.timeout.period.seconds=86400

https://kb.netapp.com/mgmt/OTV/SRA/NetApp_Storage_Replication_Adapter_4.0%2F%2F7.X_for_ONTAP_Sizing_Guide["NetApp 기술 자료 답변 1001111: ONTAP용 NetApp 스토리지 복제 어댑터 4.0/7.X 사이징 가이드"]

자세한 내용은 SAN Provider 설정 수정에 대한 VMware 설명서를 참조하십시오.

https://docs.vmware.com/en/Site-Recovery-Manager/6.5/com.vmware.srm.admin.doc/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html["VMware Site Recovery Manager 설명서: 스토리지 설정 변경"]
