---
permalink: deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords: Virtual Storage Console, Storage Replication Adapter 
summary: 여기에 제공된 지침에 따라 기존 9.10 이상의 설정에서 ONTAP 도구의 최신 릴리스로 업그레이드할 수 있습니다. 
---
= ONTAP 툴의 최신 릴리즈로 업그레이드하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여기에 제공된 지침에 따라 기존 9.10 이상 릴리스에서 최신 버전의 ONTAP 도구로 바로 업그레이드할 수 있습니다.

* 필요한 것 *

* 최신 버전의 ONTAP 도구에 대해 _.iso_file을 다운로드해야 합니다.
* 업그레이드 후 ONTAP 도구가 최적으로 작동하도록 최소 12GB RAM을 예약해야 합니다.
* vSphere Client 브라우저 캐시를 정리해야 합니다.
+
link:../deploy/task_clean_the_vsphere_cached_downloaded_plug_in_packages.html["vSphere 캐시된 다운로드 플러그인 패키지를 지웁니다"]



필요한 경우 다음 단계를 수행하여 _.iso_file을 확인하십시오. 이 단계는 선택 사항입니다.

. Entrust(OTV_ISO_CERT.PEM) openssl x509 - in OTV_ISO_CERT.pem-pubkey-nocout>csc-prod-OTV-SRA-TGZ.pub에서 발급한 코드 서명 인증서에서 공개 키를 추출합니다
. 공용 키를 사용하여 다이제스트의 서명을 확인합니다. 이 단계는 바이너리를 설치하기 전에 최종 사용자 시스템에서 수행해야 합니다. 인증서 번들은 배포 패키지에 포함되어야 합니다.)
+
OpenSSL dgst-sha256-verify csc-prod-oTV-SRA-TGZ.pub-signature NetApp-ONTAP-tools-for-VMware-vSphere-9.12-9327-upgrade-iso.SIG netapp-ontap-tools-for-vmware-vsphere-9.12-9327-upgrade.iso



기존 구축 환경에서 VASA Provider의 상태는 업그레이드 후 유지됩니다. 업그레이드 후 요구 사항에 따라 VASA Provider를 수동으로 설정하거나 해제해야 합니다. 하지만 VVol(VMware Virtual Volumes)을 사용하지 않는 경우에도 VASA Provider를 활성화하는 것이 가장 좋습니다. 이를 통해 기존 데이터 저장소 용량 할당 및 스토리지 알람을 위한 스토리지 용량 프로필을 사용할 수 있기 때문입니다.


NOTE: 기존 9.10 이상 버전에서만 최신 버전의 ONTAP 도구로 현재 위치 업그레이드를 수행할 수 있습니다.


NOTE: ONTAP 툴 9.12의 일부로 모든 스토리지 시스템 인증 및 통신 프로세스가 ONTAP 스토리지 인증서를 자동으로 신뢰하여 기본 인증에서 인증서 기반 인증으로 변경됩니다. 사용자가 수행할 작업이 없습니다.

인증서 인증 없이 스토리지 시스템을 추가하는 것은 제한됩니다.

json 파일을 사용하여 사용자 지정 생성 클러스터 범위 사용자로 스토리지 시스템을 추가하고 9.12로 업그레이드하려는 경우
업그레이드하기 전에 ONTAP CLI에서 아래 명령을 실행하여 VMware vSphere 및 ONTAP용 ONTAP 툴 간에 인증서 기반 통신을 활성화하십시오.

. _security login role create -role <existing-role-name> -cmddirname "security login show" -access all _
. _security login role create -role <existing-role-name> -cmddirname "security certificate show" -access all _
. _security login role create -role <existing-role-name> -cmddirname "security certificate install" -access all _


json 파일을 사용하여 사용자 지정된 SVM 범위의 사용자로 스토리지 시스템을 추가하고 9.12로 업그레이드하려는 경우, 그런 다음 업그레이드하기 전에 클러스터 관리자 액세스 권한이 있는 ONTAP CLI에서 다음 명령을 실행하여 VMware vSphere 및 ONTAP용 ONTAP 툴 간에 인증서 기반 통신을 설정하십시오.

. _security login role create -role <existing-role-name> -cmddirname "security certificate install" -access all -vserver <vserver-name> _
. _security login role create -role <existing-role-name> -cmddirname "security certificate show" -access all -vserver <vserver-name> _
. _security login create-user-or-group-name <user>-application http-authentication-method cert-role <existing-role-name>-vserver <vserver-name> _
. _security login create-user-or-group-name <user>-application ontapi-authentication-method cert-role <existing-role-name>-vserver <vserver-name> _


* 단계 *

. 다운로드한 _.iso_file을 ONTAP 도구에 마운트합니다.
+
.. Edit Settings * > * DVD/CD-ROM Drive * 를 클릭합니다.
.. 드롭다운 목록에서 * Datastore ISO * 파일을 선택합니다.
.. 다운로드한 _.iso_file 로 찾아 선택한 다음 * 전원을 켤 때 연결 * 확인란을 선택합니다.


. 배포된 ONTAP 도구의 요약 탭에 액세스합니다.
. 유지보수 콘솔을 시작합니다.
. "Main Menu" 프롬프트에서 * System Configuration * 에 대한 옵션 2를 입력한 다음 * Upgrade * 에 대한 옵션 8을 입력합니다.
+
업그레이드가 완료되면 ONTAP 도구가 다시 시작됩니다. ONTAP 툴은 업그레이드 전과 동일한 IP 주소를 사용하여 vCenter Server에 등록됩니다.

. ONTAP 툴을 IPv6 주소로 vCenter Server에 등록하려면 다음을 수행해야 합니다.
+
.. ONTAP 도구 등록을 취소합니다.
.. ONTAP 툴의 IPv6 주소를 * Register * 페이지를 사용하여 vCenter Server에 등록합니다.
.. 등록 후 VSC 및 VASA 공급자 인증서를 다시 생성합니다.


+

IMPORTANT: IPv6은 vCenter Server 6.7 이상에서만 지원됩니다.

. 구축된 ONTAP 툴을 보려면 vSphere Client에서 로그아웃한 후 다시 로그인하십시오.
+
.. 기존 vSphere 웹 클라이언트 또는 vSphere Client에서 로그아웃하고 창을 닫습니다.
.. vSphere Client에 로그인합니다.
+
vSphere Client에서 플러그인을 업데이트하는 데 몇 분 정도 걸릴 수 있습니다.





[NOTE]
====
* 7.0 버전의 ONTAP 툴을 최신 버전의 ONTAP 툴로 업그레이드하는 경우, 기존 VM 스토리지 정책을 편집하기 전에 먼저 스토리지 용량 프로필을 생성해야 합니다. 그렇지 않으면 값이 잘못되었거나 누락된다는 오류가 발생할 수 있습니다.
* 이전 버전에서 ONTAP 도구의 최신 릴리즈로 업그레이드할 경우 vvol.properties 파일에 'vVol.rebalance.threshold' 속성이 없는 것으로 나타납니다.
+
속성의 기본값은 85%로 설정됩니다.

* FIPS가 활성화되어 있지만 FIPS가 지원되지 않는 이전 버전의 vCenter가 있는 최신 ONTAP 툴 릴리즈로 업그레이드한 후에도 여전히 구축이 작동합니다. 하지만 vCenter를 최신 FIPS 지원 버전으로 업그레이드하고 이전 버전의 ONTAP 툴을 사용하는 경우 vCenter에서 FIPS가 비활성화되어 있는 경우에만 구축이 작동합니다.


====