---
permalink: deploy/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴에는 기본적으로 VASA 공급자 기능이 설정되어 있습니다. 각 VVol 데이터스토어에 필요한 스토리지 기능 프로필을 사용하여 VVol(VMware Virtual Volumes)\) 데이터 저장소를 구성할 수 있습니다.' 
---
= 가상 데이터 저장소를 구성하기 위해 VASA Provider를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴에는 기본적으로 VASA 공급자 기능이 설정되어 있습니다. 각 VVol 데이터 저장소에 필요한 스토리지 기능 프로필을 사용하여 VVol(VMware Virtual Volumes) 데이터 저장소를 구성할 수 있습니다.

* 필요한 것 *

* vCenter Server 인스턴스를 설정하고 ESXi를 구성해야 합니다.
* ONTAP 툴을 구축해야 합니다.


* 이 작업에 대한 정보 *

ONTAP 툴의 9.7.1 릴리즈로 업그레이드하기 전에 VASA 공급자 기능이 비활성화된 경우 업그레이드 후에도 VASA 공급자 기능이 비활성화된 상태로 유지됩니다. 이 릴리즈를 사용하면 VVOL 데이터 저장소에 대한 VVol 복제 기능을 활성화할 수 있습니다.

* 단계 *

. VMware vSphere의 웹 사용자 인터페이스에 로그인합니다.
. vSphere 클라이언트에서 * 메뉴 * > * ONTAP 툴 콘솔 * 을 클릭합니다.
. 설정 * 을 클릭합니다.
. 관리 설정 탭에서 * 기능 관리 * 를 클릭합니다.
. Manage Capabilities 대화 상자에서 사용할 VASA Provider 확장을 선택합니다.
. VVOL 데이터 저장소의 복제 기능을 사용하려면 * VVol 복제 활성화 * 전환 버튼을 사용합니다.
. ONTAP 도구의 IP 주소와 관리자 암호를 입력한 다음 * 적용 * 을 클릭합니다.
+

NOTE: VASA Provider 확장을 설정한 후에도 VASA Provider 상태가 ""Offline""으로 표시되면 ""/var/log/vmware/vmware-SPS/SPS.log" 파일에서 VASA Provider와의 연결 오류를 확인하거나 ""VMware-SPS"" 서비스를 다시 시작하십시오.





== ONTAP 9.6 이하 릴리스에서 OnCommand API 서비스를 등록합니다

ONTAP 9.6 이하를 사용하는 경우, VASA Provider용 OnCommand API Services를 등록하여 VVol VM 및 데이터 저장소 보고서에 대한 데이터를 얻은 경우에만 VVol 대시보드에서 VVol(VMware Virtual Volumes) 데이터 저장소 및 가상 시스템의 세부 정보를 표시할 수 있습니다.

* 필요한 것 *

NetApp Support 사이트에서 OnCommand API Services 2.1 이상을 다운로드해야 합니다.


NOTE: ONTAP 9.3 이상을 사용하여 SAN VVOL 데이터 저장소 및 가상 머신을 구성한 경우에만 VVol 대시보드에 성능 메트릭이 표시됩니다.

* 단계 *

. ONTAP 도구 홈 페이지에서 * 설정 * 을 클릭합니다.
. 관리 설정 탭에서 * 확장 관리 * 를 클릭합니다.
. OnCommand API 서비스 등록 슬라이더를 사용하여 OnCommand API 서비스를 활성화합니다.
. OnCommand API 서비스의 IP 주소, 서비스 포트 및 자격 증명을 입력합니다.
+
VASA Provider Extensions 관리 대화 상자를 사용하여 다음 사항을 수정할 수도 있습니다.

+
** 자격 증명이 변경된 경우 OnCommand API 서비스 등록을 업데이트하려면
** VVol 대시보드가 더 이상 필요하지 않은 경우 OnCommand API Services의 등록을 취소합니다.
+
VASA Provider에 대한 OnCommand API 서비스 등록을 제거하려면 OnCommand API 서비스 등록 확인란의 선택을 해제해야 합니다.



. 적용 * 을 클릭합니다.
+
ONTAP API 서비스 등록이 완료된 후에만 VVOL 대시보드가 OnCommand 9.6 또는 이전 SAN VVOL 데이터 저장소에 대한 메트릭을 표시합니다.



* 관련 정보 *

https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]
