---
permalink: deploy/task_install_the_nfs_vaai_plug_in.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴의 GUI를 사용하여 VAAI(VMware vStorage APIs for Array Integration)용 NetApp NFS 플러그인을 설치할 수 있습니다.' 
---
= NFS VAAI 플러그인을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴의 GUI를 사용하여 VAAI(VMware vStorage APIs for Array Integration)용 NetApp NFS 플러그인을 설치할 수 있습니다.

* 필요한 것 *

* VAAI용 NFS 플러그인의 설치 패키지를 다운로드해야 합니다 (``.vib`)NetApp Support 사이트 를 클릭합니다. https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]
* ESXi 호스트 6.5 이상 및 ONTAP 9.1 이상을 설치해야 합니다.
* ESXi 호스트의 전원을 켜고 NFS 데이터 저장소를 마운트해야 합니다.
* "다카무버.HardwareAcceleratedMove", "다카무버.HardwareAcceleratedInit", "VMFS3.HardwareAcceleratedLocking" 호스트 설정의 값을 ""1"로 설정해야 합니다.
+
이러한 값은 권장 설정 대화 상자가 업데이트될 때 ESXi 호스트에서 자동으로 설정됩니다.

* "vserver NFS modify -vserver vserver_name -vStorage enabled" 명령을 사용하여 SVM(스토리지 가상 시스템)에서 vStorage 옵션을 활성화해야 합니다.
* NetApp NFS VAAI 플러그인 2.0을 사용하는 경우 ESXi 7.0 업데이트1 이상이 있어야 합니다.
* vSphere 6.5가 더 이상 사용되지 않고 vSphere 8.x는 지원되지 않으므로 vSphere 7.x 릴리즈가 있어야 합니다.
* vSphere 8.x는 NetApp NFS VAAI 플러그인 2.0.1(빌드 16)에서 지원됩니다.


* 단계 *

. 의 이름을 바꿉니다 `.vib` NetApp Support 사이트에서 NetAppNasPlugin.vib로 다운로드한 파일로, ONTAP 도구에서 사용하는 미리 정의된 이름과 일치합니다.
. ONTAP 도구 홈 페이지에서 * 설정 * 을 클릭합니다.
. NFS VAAI Tools * 탭을 클릭합니다.
. 기존 버전 * 섹션에서 * 변경 * 을 클릭합니다.
. 이름이 바뀐 '.vib' 파일을 찾아 선택한 다음 * 업로드 * 를 클릭하여 파일을 ONTAP 도구에 업로드합니다.
. ESXi 호스트에 설치 섹션에서 NFS VAAI 플러그인을 설치할 ESXi 호스트를 선택한 다음 * 설치 * 를 클릭합니다.
+
화면의 지시에 따라 설치를 완료해야 합니다. vSphere Web Client의 Tasks 섹션에서 설치 진행률을 모니터링할 수 있습니다.

. 설치가 완료되면 ESXi 호스트를 재부팅합니다.
+
ESXi 호스트를 재부팅하면 ONTAP 툴이 자동으로 NFS VAAI 플러그인을 감지합니다. 플러그인을 활성화하기 위해 추가 단계를 수행할 필요가 없습니다.


