---
permalink: concepts/concept_configure_high_availability_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'ONTAP 툴은 고가용성 \(HA\) 구성을 지원하여 장애 시 ONTAP 툴의 무중단 기능을 제공합니다.' 
---
= ONTAP 툴에 대한 고가용성을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 툴은 고가용성(HA) 구성을 지원하여 장애 발생 시 ONTAP 툴의 무중단 기능을 제공합니다.

ONTAP 툴은 VMware vSphere HA(고가용성) 기능과 vSphere FT(내결함성) 기능을 사용하여 고가용성을 제공합니다. 고가용성(HA) 솔루션을 통해 다음과 같은 원인으로 인한 운영 중단으로부터 신속하게 복구할 수 있습니다.

* 호스트 오류입니다
* 네트워크 오류입니다
* 가상 머신 장애(게스트 OS 장애)
* 응용 프로그램(ONTAP 도구)이 충돌합니다


고가용성을 제공하기 위해 ONTAP 툴에 대한 추가 구성이 필요하지 않습니다. 요구 사항에 따라 vCenter Server 및 ESXi 호스트만 VMware vSphere HA 기능 또는 vSphere FT 기능으로 구성해야 합니다. HA와 FT에는 모두 공유 스토리지와 함께 클러스터 호스트가 필요합니다. FT는 추가적인 요구 사항과 제한 사항이 있습니다.

ONTAP 툴은 VMware vSphere HA 솔루션 및 vSphere FT 솔루션과 함께 ONTAP 툴 서비스를 항상 실행할 수 있도록 지원합니다. ONTAP 도구 감시 프로세스는 세 가지 서비스를 주기적으로 모니터링하여 어떤 종류의 오류가 감지되면 자동으로 다시 시작합니다. 이렇게 하면 응용 프로그램 오류를 방지할 수 있습니다.


NOTE: vCenter HA는 ONTAP 툴에서 지원되지 않습니다.



== VMware vSphere HA

HA(고가용성)를 위해 VMware vSphere용 ONTAP 툴을 구축할 vSphere 환경을 구성할 수 있습니다. VMware HA 기능은 가상 환경에서 하드웨어 장애 및 운영 체제 장애로부터 페일오버 보호 기능을 제공합니다.

VMware HA 기능은 가상 시스템을 모니터링하여 운영 체제 장애 및 하드웨어 장애를 감지합니다. 장애가 감지되면 VMware HA 기능은 리소스 풀의 다른 물리적 서버에서 가상 머신을 다시 시작합니다. 서버 오류가 감지되면 수동 개입이 필요하지 않습니다.

VMware HA 구성 절차는 vCenter Server 버전에 따라 다릅니다. 예를 들어 다음 참조 링크를 사용하여 필요한 vCenter Server 버전을 선택하여 VMware HA 구성 단계를 볼 수 있습니다.

https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-availability/GUID-5432CA24-14F1-44E3-87FB-61D937831CF6.html["VMware vSphere 설명서: vSphere HA 클러스터 생성 및 사용"]



== VMware vSphere 내결함성

VMware vSphere FT(Fault Tolerance) 기능은 더 높은 수준의 고가용성(HA)을 제공하며 데이터 또는 연결 손실 없이 가상 머신을 보호할 수 있습니다. vCenter Server에서 vSphere FT for ONTAP 툴을 설정하거나 해제해야 합니다.

vSphere 라이센스가 ONTAP 툴에 필요한 vCPU 수로 FT를 지원하는지 확인합니다(대규모 환경의 경우 vCPU 2개 이상, vCPU 4개).

vSphere FT를 사용하면 서버 장애가 발생하더라도 가상 머신을 지속적으로 운영할 수 있습니다. 가상 머신에서 vSphere FT가 설정되면 DRS(Distributed Resource Scheduler)가 선택한 다른 호스트(보조 가상 머신)에 운영 가상 머신의 복제본이 자동으로 생성됩니다. DRS가 활성화되어 있지 않으면 사용 가능한 호스트에서 대상 호스트가 선택됩니다. vSphere FT는 운영 가상 머신과 보조 가상 머신을 잠금 단계 모드로 작동하여 각 가상 머신이 운영 가상 머신의 실행 상태를 보조 가상 머신에 미러링합니다.

운영 가상 시스템에 장애를 일으키는 하드웨어 장애가 있는 경우 보조 가상 머신이 운영 가상 머신이 중지된 위치를 즉시 감지합니다. 보조 가상 시스템은 네트워크 연결, 트랜잭션 또는 데이터의 손실 없이 계속 실행됩니다.

시스템은 vCenter Server 인스턴스에 대해 vSphere FT를 구성하기 위한 CPU 요구 사항, 가상 머신 제한 요구 사항 및 라이센스 요구 사항을 충족해야 합니다.

HA를 구성하는 절차는 vCenter Server 버전에 따라 다릅니다. 예를 들어 다음 참조 링크를 사용하여 필요한 vCenter Server 버전을 선택하여 HA 구성 단계를 볼 수 있습니다.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.avail.doc/GUID-57929CF0-DA9B-407A-BF2E-E7B72708D825.html["VMware vSphere 설명서: 내결함성 요구 사항, 제한 사항 및 라이센스"]
