---
permalink: concepts/concept_how_to_configure_data_ontap_role_based_access_control_for_vsc_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴과 함께 역할 기반 액세스 제어를 사용하려면 스토리지 시스템에서 ONTAP 역할 기반 액세스 제어\(RBAC\)를 구성해야 합니다. ONTAP RBAC 기능을 사용하여 액세스 권한이 제한된 사용자 지정 사용자 계정을 하나 이상 생성할 수 있습니다.' 
---
= VMware vSphere용 ONTAP 툴에 대한 ONTAP 역할 기반 액세스 제어를 구성하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴과 함께 역할 기반 액세스 제어를 사용하려면 스토리지 시스템에서 RBAC(ONTAP 역할 기반 액세스 제어)를 구성해야 합니다. ONTAP RBAC 기능을 사용하여 액세스 권한이 제한된 사용자 지정 사용자 계정을 하나 이상 생성할 수 있습니다.

VMware vSphere 및 SRA용 ONTAP 툴은 클러스터 레벨 또는 SVM(스토리지 가상 머신) SVM 레벨에서 스토리지 시스템에 액세스할 수 있습니다. 클러스터 레벨에서 스토리지 시스템을 추가하는 경우 필요한 모든 기능을 제공하려면 admin 사용자의 자격 증명을 제공해야 합니다. SVM 세부 정보를 직접 추가하여 스토리지 시스템을 추가하는 경우 "'vsadmin'' 사용자에게 특정 작업을 수행하는 데 필요한 모든 역할과 기능이 없다는 점을 알아야 합니다.

VASA Provider는 클러스터 레벨에서만 스토리지 시스템에 액세스할 수 있습니다. 특정 스토리지 컨트롤러에 VASA Provider가 필요한 경우 ONTAP 툴 또는 SRA를 사용하는 경우에도 클러스터 레벨에서 VMware vSphere용 ONTAP 툴에 스토리지 시스템을 추가해야 합니다.

새 사용자를 생성하고 클러스터 또는 SVM을 ONTAP 툴에 연결하려면 다음을 수행해야 합니다.

* ONTAP System Manager 9.8P1 이상을 사용하여 클러스터 관리자 또는 SVM 관리자 역할을 생성합니다. 을 참조하십시오 link:../configure/task_configure_user_role_and_privileges.html["사용자 역할 및 권한을 구성합니다"] 를 참조하십시오.
* 할당된 역할과 ONTAP를 사용하여 적절한 애플리케이션 세트를 가진 사용자를 생성합니다
+
ONTAP 툴을 위한 스토리지 시스템을 구성하려면 이러한 스토리지 시스템 자격 증명이 필요합니다. ONTAP 툴에 자격 증명을 입력하여 ONTAP 툴에 대한 스토리지 시스템을 구성할 수 있습니다. 이러한 자격 증명을 사용하여 스토리지 시스템에 로그인할 때마다 자격 증명을 생성하는 동안 ONTAP에서 설정한 ONTAP 툴 기능에 대한 권한이 부여됩니다.

* 스토리지 시스템을 VMware vSphere용 ONTAP 툴에 추가하고 방금 생성한 사용자의 자격 증명을 제공합니다




== ONTAP 툴 역할

ONTAP 도구는 ONTAP 권한을 다음과 같은 ONTAP 도구 역할로 분류합니다.

* 탐색
+
연결된 모든 스토리지 컨트롤러를 검색할 수 있습니다

* 스토리지 생성
+
볼륨 및 LUN(Logical Unit Number) 생성 지원

* 스토리지 수정
+
스토리지 시스템의 크기 조정 및 중복 제거를 설정합니다

* 스토리지 폐기
+
볼륨 및 LUN을 소멸하도록 설정합니다





== VASA 공급자 역할

클러스터 수준에서는 정책 기반 관리만 생성할 수 있습니다. 스토리지 용량 프로필을 사용하여 정책을 기반으로 스토리지를 관리할 수 있습니다.



== SRA 역할

SRA에서는 ONTAP 권한을 클러스터 수준 또는 SVM 수준에서 SAN 또는 NAS 역할로 분류합니다. 이를 통해 사용자는 SRM 작업을 실행할 수 있습니다.

ONTAP 툴은 ONTAP 툴에 클러스터를 추가할 때 ONTAP RBAC 역할에 대한 초기 권한 검증을 수행합니다. SVM 사용자 스토리지 IP를 추가한 경우 ONTAP 툴이 초기 검증을 수행하지 않습니다. ONTAP 도구는 나중에 작업 워크플로에서 권한을 확인하고 적용합니다.
