---
permalink: concepts/concept_manage_disaster_recovery_setup_using_srm.html 
sidebar: sidebar 
keywords:  
summary: 'VMware의 SRM\(Site Recovery Manager)과 함께 vCenter Server에서 재해 복구 설정을 만들고 관리할 수 있습니다.' 
---
= 재해 복구 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware의 SRM(Site Recovery Manager)과 함께 vCenter Server에서 재해 복구 설정을 생성하고 관리할 수 있습니다.

VASA Provider는 SRA(Storage Replication Adapter)의 기능을 기본적으로 제공합니다. 데이터 센터에서 VVOL 데이터 저장소를 구성한 경우 VVOL 데이터 저장소의 복구를 위해 SRA를 별도로 설치할 필요가 없습니다. SRM(Site Recovery Manager)에서는 보호 사이트와 복구 사이트를 페어링해야 합니다. 사이트 페어링이 발생한 후 SRM 구성의 다음 부분에서는 SRM이 스토리지 시스템과 통신하여 디바이스 및 디바이스 복제를 검색할 수 있도록 스토리지 쌍을 설정하는 작업을 수행합니다. 스토리지 쌍을 구성하려면 먼저 SRM에서 사이트 쌍을 만들어야 합니다.

이번 릴리즈의 ONTAP 도구에서는 재해 복구를 위해 동기식 SnapMirror 구성을 사용하는 옵션을 제공합니다.


NOTE: VMware SRM(Site Recovery Manager)은 VVOL 데이터 저장소의 재해 복구를 관리하기 위해 SRA를 사용하지 않습니다. 대신 VASA Provider를 사용하여 ONTAP 9.7 이상의 클러스터에서 VVOL 데이터 저장소의 복제 및 페일오버 제어를 수행할 수 있습니다.

을 참조하십시오 link:../protect/task_enable_storage_replication_adapter.html["스토리지 복제 어댑터를 활성화합니다"] 섹션을 참조하십시오.

.Quick_Resync 기능 활성화
SRA에서 Reprotect 및 Restore 작업을 수행하기 위해 quick_resync 플래그를 활성화할 수 있습니다. 이 옵션은 비동기식 SnapMirror 관계가 있는 볼륨에서 지원되는 데이터 저장소에만 적용됩니다. quick_resync 플래그를 사용하면 새 데이터가 전송되기 전에 재동기화로 스토리지 효율성 오버헤드가 발생하지 않으므로 대상 볼륨의 재동기화 시간을 단축할 수 있습니다. quick_resync는 기본적으로 설정되어 있지 않습니다. quick_resync 플래그를 활성화하는 것이 좋습니다.

* 재동기화의 소스에 볼륨 효율성이 설정되지 않은 경우
* 재동기화 시간을 줄이는 것이 네트워크에서 가능한 모든 스토리지 효율성을 유지하는 것보다 더 중요합니다.


다음 단계에 따라 quick_resync 플래그를 활성화합니다.

.단계
. https://<IP address>: 9083_에서 제어판에 로그인하고 웹 기반 CLI 인터페이스를 클릭합니다.
. 명령을 실행합니다 `vp updateconfig -key=snapmirror.quick.resync.enabled -value=true`.
. 명령을 실행합니다 `vp reloadconfig`.

