---
permalink: concepts/concept_virtual_storage_console_overview.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴은 NetApp 스토리지 시스템을 사용하는 VMware 환경에서 가상 머신에 대한 엔드 투 엔드 라이프사이클 관리를 제공합니다. 관리자는 vCenter Server 내의 스토리지를 직접 관리할 수 있으므로 VMware 환경의 스토리지 및 데이터 관리가 간소화됩니다. 
---
= ONTAP 도구 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴은 NetApp 스토리지 시스템을 사용하는 VMware 환경에서 가상 머신에 대한 엔드 투 엔드 라이프사이클 관리를 제공합니다. 관리자는 vCenter Server 내의 스토리지를 직접 관리할 수 있으므로 VMware 환경의 스토리지 및 데이터 관리가 간소화됩니다.

ONTAP 툴은 vSphere 클라이언트와 통합되며 SSO(Single Sign-On) 서비스를 사용할 수 있습니다. vCenter Server 인스턴스가 여러 개 있는 환경에서는 관리하려는 각 vCenter Server 인스턴스에 고유한 ONTAP 툴 등록 인스턴스가 있어야 합니다.

ONTAP 툴의 각 구성 요소는 스토리지를 보다 효율적으로 관리하는 데 도움이 되는 기능을 제공합니다.

VMware vSphere Client 원격 플러그인 툴은 vCenter Server 내부에서 실행할 필요 없이 플러그인 기능을 vSphere Client에 통합하도록 설계되었습니다. 따라서 플러그인을 격리하고 대규모 vSphere 환경에서 작동하는 플러그인을 스케일아웃할 수 있습니다.



== 가상 스토리지 콘솔(VSC)

VSC를 사용하면 다음 작업을 수행할 수 있습니다.

* SRA 및 VASA Provider가 모두 활용할 수 있도록 스토리지 컨트롤러를 추가하고, 자격 증명을 할당하고, VSC의 스토리지 컨트롤러에 대한 권한을 설정합니다
* 데이터 저장소를 프로비저닝합니다
* vCenter Server 환경에서 데이터 저장소 및 가상 머신의 성능을 모니터링합니다
* 두 가지 수준에서 역할 기반 액세스 제어(RBAC)를 사용하여 vCenter Server 객체에 대한 관리자 액세스를 제어합니다.
+
** 가상 머신 및 데이터 저장소와 같은 vSphere 객체
+
이러한 객체는 vCenter Server RBAC를 사용하여 관리됩니다.

** ONTAP 스토리지
+
스토리지 시스템은 ONTAP RBAC를 사용하여 관리합니다.



* NetApp 스토리지에 연결된 ESXi 호스트의 호스트 설정을 보고 업데이트합니다


VAAI(VMware vStorage APIs for Array Integration)용 NFS 플러그인을 사용하면 VSC 프로비저닝 작업을 더 유용하게 활용할 수 있습니다. VAAI용 NFS 플러그인은 ESXi 호스트에 설치된 VMware 가상 디스크 라이브러리를 통합하는 소프트웨어 라이브러리입니다. VMware VAAI 패키지를 사용하면 특정 작업을 물리적 호스트에서 스토리지 시스템으로 오프로드할 수 있습니다. 스토리지 레벨에서 씬 프로비저닝 및 하드웨어 가속 등의 작업을 수행하여 ESXi 호스트의 워크로드를 줄일 수 있습니다. 복사본 오프로드 기능 및 공간 예약 기능으로 VSC 작업의 성능을 향상합니다.

VAAI용 NetApp NFS 플러그인은 VSC와 함께 제공되지 않습니다. 하지만 플러그인 설치 패키지를 다운로드하여 NetApp Support 사이트에서 플러그인 설치 지침을 확인할 수 있습니다.



== VASA 공급자

VASA Provider for ONTAP는 VMware VASA(vSphere APIs for Storage Awareness)를 사용하여 VMware vSphere에서 사용하는 스토리지에 대한 정보를 vCenter Server로 전송합니다. ONTAP 툴에는 VASA Provider가 VSC와 통합되어 있습니다. VASA Provider를 사용하면 다음 작업을 수행할 수 있습니다.

* VVol(VMware Virtual Volumes) 데이터 저장소 프로비저닝
* 사용자 환경에 대한 다양한 스토리지 서비스 수준 목표(SLO)를 정의하는 스토리지 기능 프로필을 생성하여 사용합니다
* 데이터 저장소와 스토리지 용량 프로필 간의 규정 준수 여부를 확인합니다
* 볼륨 및 애그리게이트가 임계값 제한에 도달할 때 경고를 표시하도록 알람을 설정합니다
* VVol 데이터스토어에 생성된 가상 머신 디스크(VMDK)와 가상 머신의 성능을 모니터링합니다




== SRA(Storage Replication Adapter)

SRA를 활성화하고 VMware SRM(Site Recovery Manager)과 함께 사용하면 장애 발생 시 vCenter Server 데이터 저장소 및 가상 시스템을 복구할 수 있습니다. SRA를 사용하면 장애 발생 시 재해 복구를 위해 보호된 사이트와 복구 사이트에 ABR(어레이 기반 복제)을 사용할 수 있습니다.

* 관련 정보 *

https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]
