---
permalink: concepts/concept_standard_roles_packaged_with_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 'vCenter Server 권한 및 역할 기반 액세스 제어\(RBAC\)로 작업을 단순화하기 위해 ONTAP 툴은 주요 ONTAP 툴 작업을 수행할 수 있는 표준 ONTAP 툴 역할을 제공합니다. 또한 정보를 볼 수는 있지만 작업을 수행할 수 없는 읽기 전용 역할도 있습니다.' 
---
= ONTAP 툴과 함께 패키지로 제공되는 표준 역할입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server 권한 및 역할 기반 액세스 제어(RBAC)로 작업을 단순화하기 위해 ONTAP 툴은 주요 ONTAP 툴 작업을 수행할 수 있는 표준 ONTAP 툴 역할을 제공합니다. 또한 정보를 볼 수는 있지만 작업을 수행할 수 없는 읽기 전용 역할도 있습니다.

표준 ONTAP 툴 역할에는 필요한 ONTAP 툴별 권한과 사용자가 ONTAP 툴 작업을 수행하는 데 필요한 기본 vCenter Server 권한이 모두 있습니다. 또한 지원되는 모든 vCenter Server 버전에서 필요한 권한을 가질 수 있도록 역할이 설정됩니다.

관리자는 필요에 따라 이러한 역할을 사용자에게 할당할 수 있습니다.


NOTE: ONTAP 도구를 최신 버전으로 업그레이드하면 표준 역할이 자동으로 업그레이드되어 새 버전의 도구와 함께 작동합니다.

vSphere 클라이언트 홈 페이지에서 * 역할 * 을 클릭하여 ONTAP 툴 표준 역할을 볼 수 있습니다.

ONTAP 도구에서 제공하는 역할을 사용하여 다음 작업을 수행할 수 있습니다.

|===


| * 역할 * | * 설명 * 


 a| 
VSC 관리자
 a| 
모든 ONTAP 툴 작업을 수행하는 데 필요한 모든 기본 vCenter Server 권한 및 ONTAP 툴별 권한을 제공합니다.



 a| 
VSC 읽기 전용
 a| 
ONTAP 도구에 대한 읽기 전용 액세스를 제공합니다. 이러한 사용자는 액세스가 제어되는 ONTAP 도구 작업을 수행할 수 없습니다.



 a| 
VSC 프로비저닝
 a| 
스토리지를 프로비저닝하는 데 필요한 모든 기본 vCenter Server 권한 및 ONTAP 툴별 권한을 제공합니다. 다음 작업을 수행할 수 있습니다.

* 새 데이터 저장소를 생성합니다
* 데이터 저장소를 제거합니다
* 스토리지 용량 프로필에 대한 정보를 봅니다


|===


== ONTAP 도구 표준 역할 사용 지침

VMware vSphere 역할에 대한 표준 ONTAP 툴을 사용할 경우 따라야 할 몇 가지 지침이 있습니다.

표준 역할을 직접 수정해서는 안 됩니다. 이 경우 ONTAP 도구는 업그레이드할 때마다 변경 내용을 덮어씁니다. 설치 프로그램은 ONTAP 도구를 업그레이드할 때마다 표준 역할 정의를 업데이트합니다. 이렇게 하면 현재 사용 중인 버전의 ONTAP 툴 및 지원되는 모든 버전의 vCenter Server에 대한 역할이 최신 상태로 유지됩니다.

그러나 표준 역할을 사용하여 사용자 환경에 맞는 역할을 만들 수 있습니다. 이렇게 하려면 ONTAP 도구 표준 역할을 복사한 다음 복사된 역할을 편집해야 합니다. 새 역할을 만들면 ONTAP 도구 Windows 서비스를 다시 시작하거나 업그레이드할 때도 이 역할을 유지할 수 있습니다.

ONTAP 도구 표준 역할을 사용하는 몇 가지 방법은 다음과 같습니다.

* 모든 ONTAP 도구 작업에 표준 ONTAP 도구 역할을 사용합니다.
+
이 시나리오에서 표준 역할은 사용자가 ONTAP 도구 작업을 수행하는 데 필요한 모든 권한을 제공합니다.

* 역할을 결합하여 사용자가 수행할 수 있는 작업을 확장합니다.
+
표준 ONTAP 툴 역할이 환경에 대해 너무 세밀하게 제공되면 여러 역할을 포함하는 상위 레벨 그룹을 생성하여 역할을 확장할 수 있습니다.

+
사용자가 추가적인 기본 vCenter Server 권한이 필요한 ONTAP 이외의 다른 툴 작업을 수행해야 하는 경우, 이러한 권한을 제공하는 역할을 생성하여 그룹에도 추가할 수 있습니다.

* 보다 세분화된 역할을 만듭니다.
+
회사에서 표준 ONTAP 도구 역할보다 제한적인 역할을 구현해야 하는 경우 ONTAP 도구 역할을 사용하여 새 역할을 만들 수 있습니다.

+
이 경우 필요한 ONTAP 도구 역할을 클론한 다음 사용자에게 필요한 권한만 있도록 클론 생성된 역할을 편집합니다.


