---
permalink: concepts/concept_guidelines_for_using_vsc_standard_roles.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 역할을 위한 표준 ONTAP ® 툴을 사용할 경우 따라야 할 몇 가지 지침이 있습니다. 
---
= ONTAP 도구 표준 역할 사용 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 역할을 위한 표준 ONTAP ® 툴을 사용할 경우 따라야 할 몇 가지 지침이 있습니다.

표준 역할을 직접 수정해서는 안 됩니다. 이렇게 하면 ONTAP 도구를 업그레이드할 때마다 ONTAP 도구가 변경 내용을 덮어씁니다. 설치 프로그램은 ONTAP 도구를 업그레이드할 때마다 표준 역할 정의를 업데이트합니다. 이렇게 하면 현재 사용 중인 버전의 ONTAP 툴 및 지원되는 모든 버전의 vCenter Server에 대한 역할이 최신 상태로 유지됩니다.

그러나 표준 역할을 사용하여 사용자 환경에 맞는 역할을 만들 수 있습니다. 이렇게 하려면 ONTAP 도구 표준 역할을 복사한 다음 복사된 역할을 편집해야 합니다. 새 역할을 만들면 ONTAP 도구 Windows 서비스를 다시 시작하거나 업그레이드할 때도 이 역할을 유지할 수 있습니다.

ONTAP 도구 표준 역할을 사용하는 몇 가지 방법은 다음과 같습니다.

* 모든 ONTAP 도구 작업에 표준 ONTAP 도구 역할을 사용합니다.
+
이 시나리오에서 표준 역할은 사용자가 ONTAP 도구 작업을 수행하는 데 필요한 모든 권한을 제공합니다.

* 역할을 결합하여 사용자가 수행할 수 있는 작업을 확장합니다.
+
표준 ONTAP 툴 역할이 환경에 대해 너무 세밀하게 제공되면 여러 역할을 포함하는 상위 레벨 그룹을 생성하여 역할을 확장할 수 있습니다.

+
사용자가 추가적인 기본 vCenter Server 권한이 필요한 ONTAP 이외의 다른 툴 작업을 수행해야 하는 경우, 이러한 권한을 제공하는 역할을 생성하여 그룹에도 추가할 수 있습니다.

* 보다 세분화된 역할을 만듭니다.
+
회사에서 표준 ONTAP 도구 역할보다 제한적인 역할을 구현해야 하는 경우 ONTAP 도구 역할을 사용하여 새 역할을 만들 수 있습니다.

+
이 경우 필요한 ONTAP 도구 역할을 클론한 다음 사용자에게 필요한 권한만 있도록 클론 생성된 역할을 편집합니다.


