---
permalink: configure/concept_configure_storage_systems_for_ontap_tools_for_vmware_vsphere.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 시스템을 ONTAP 툴에 추가하고 필요한 경우 ONTAP 툴 인터페이스를 사용하여 기본 자격 증명을 설정해야 합니다. 
---
= ONTAP 툴을 위한 스토리지 시스템 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템을 ONTAP 툴에 추가하고 필요한 경우 ONTAP 툴 인터페이스를 사용하여 기본 자격 증명을 설정해야 합니다.

VMware vSphere용 ONTAP 툴은 스토리지 시스템을 검색하고 스토리지 자격 증명을 설정하는 단일 메커니즘을 제공합니다. 자격 증명은 ONTAP 툴 사용자가 스토리지 시스템을 사용하여 작업을 수행할 수 있도록 필요한 ONTAP 권한을 제공합니다.

ONTAP 툴이 스토리지 리소스를 표시하고 관리하기 전에 먼저 ONTAP 툴이 스토리지 시스템을 검색해야 합니다. 검색 프로세스 중에 스토리지 시스템에 대한 ONTAP 자격 증명을 제공해야 합니다. 각 스토리지 시스템에 할당된 사용자 이름 및 암호 쌍과 연결된 권한(또는 역할)입니다. 이러한 사용자 이름 및 암호 쌍은 ONTAP 역할 기반 액세스 제어(RBAC)를 사용하며 ONTAP 내에서 설정해야 합니다. ONTAP 도구 내에서는 이러한 자격 증명을 변경할 수 없습니다. ONTAP 시스템 관리자를 사용하여 ONTAP RBAC 역할을 정의할 수 있습니다.


NOTE: 관리자로 로그인하면 해당 스토리지 시스템에 대한 모든 권한이 자동으로 부여됩니다.

스토리지 시스템을 ONTAP 툴에 추가할 때 스토리지 시스템의 IP 주소와 해당 시스템과 연결된 사용자 이름 및 암호 쌍을 제공해야 합니다. 스토리지 시스템 검색 프로세스 중에 ONTAP 툴에서 사용할 기본 자격 증명을 설정하거나 스토리지 시스템이 검색될 때 자격 증명을 수동으로 입력할 수 있습니다. ONTAP 툴에 추가된 스토리지 시스템의 세부 정보는 배포에서 사용하도록 설정한 확장 기능으로 자동 푸시됩니다. VASA Provider 및 SRA(Storage Replication Adapter)에 스토리지를 수동으로 추가할 필요가 없습니다. ONTAP 툴과 SRA는 모두 클러스터 레벨 및 SVM(스토리지 가상 머신) 레벨에서 자격 증명 추가를 지원합니다. VASA Provider는 스토리지 시스템을 추가하기 위한 클러스터 레벨 자격 증명만 지원합니다. 스토리지 시스템을 추가할 때 ONTAP 툴 플러그인과 스토리지 시스템 간의 통신이 상호 인증되어야 합니다.

환경에 vCenter Server 인스턴스가 여러 개 포함된 경우 스토리지 시스템 페이지에서 스토리지 시스템을 ONTAP 툴에 추가하면 스토리지 시스템을 추가할 vCenter Server 인스턴스를 지정할 수 있는 vCenter Server 상자가 스토리지 시스템 추가 대화 상자에 표시됩니다. 데이터 센터 이름을 마우스 오른쪽 버튼으로 클릭하여 스토리지 시스템을 추가하는 경우 서버가 이미 해당 데이터 센터에 연결되어 있으므로 vCenter Server 인스턴스를 지정할 수 있는 옵션이 없습니다.

검색은 다음 방법 중 하나로 수행됩니다. 각각의 경우 새로 검색된 스토리지 시스템에 대한 자격 증명을 제공해야 합니다.

* ONTAP 툴 서비스가 시작되면 ONTAP 툴이 자동 백그라운드 검색 프로세스를 시작합니다.
* 스토리지 시스템 * 페이지 또는 호스트 또는 데이터 센터에서 모두 다시 검색 버튼을 클릭하여 * 작업 * 메뉴( * 작업 * > * NetApp ONTAP 툴 * > * 호스트 및 스토리지 데이터 업데이트 *)에서 선택할 수 있습니다. '개요' 섹션의 * 시작하기 * 탭에서 * 검색 * 을 클릭할 수도 있습니다.


모든 ONTAP 도구 기능을 사용하려면 특정 권한이 있어야 작업을 수행할 수 있습니다. ONTAP 역할과 연결된 자격 증명을 기준으로 사용자가 수행할 수 있는 작업을 제한할 수 있습니다. 스토리지 시스템 사용자 이름과 암호 쌍이 같은 모든 사용자는 동일한 스토리지 시스템 자격 증명 세트를 공유하며 동일한 작업을 수행할 수 있습니다.
