---
permalink: configure/concept_configure_storage_capability_profiles.html 
sidebar: sidebar 
keywords: storage capability profiles 
summary: VASA Provider for ONTAP를 사용하면 스토리지 기능 프로파일을 생성하여 스토리지에 매핑할 수 있습니다. 따라서 스토리지 전체에서 일관성을 유지할 수 있습니다. 또한 VASA Provider를 사용하여 스토리지와 스토리지 용량 프로필 간의 규정 준수를 확인할 수도 있습니다. 
---
= 스토리지 용량 프로필 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Provider for ONTAP를 사용하면 스토리지 기능 프로파일을 생성하여 스토리지에 매핑할 수 있습니다. 따라서 스토리지 전체에서 일관성을 유지할 수 있습니다. 또한 VASA Provider를 사용하여 스토리지와 스토리지 용량 프로필 간의 규정 준수를 확인할 수도 있습니다.

스토리지 기능은 특정 수준의 스토리지 성능, 스토리지 효율성 및 스토리지 기능과 연결된 스토리지 오브젝트의 암호화와 같은 기타 기능을 식별하는 스토리지 시스템 속성의 집합입니다.

기존 데이터 저장소의 경우 스토리지 용량 프로필을 사용하여 공통 특성을 사용하여 데이터 저장소를 일관되게 생성하고 QoS 정책을 해당 데이터 저장소에 할당할 수 있습니다. 프로비저닝 VSC를 사용하면 스토리지 기능 프로필과 일치하는 클러스터, SVM, 애그리게이트를 표시할 수 있습니다. Storage Mapping 메뉴의 * global Auto-generate profiles * 옵션을 사용하여 기존 기존 데이터 저장소에서 스토리지 용량 프로파일을 생성할 수 있습니다. 프로필이 생성된 후에는 VSC를 사용하여 프로필과의 데이터 저장소 규정 준수를 모니터링할 수 있습니다.


NOTE: VVOL 데이터 저장소는 직접 SVM에서 지원되지 않습니다.

VVol 데이터스토어와 함께 사용할 경우 프로비저닝 마법사는 여러 스토리지 기능 프로필을 사용하여 데이터 저장소에 서로 다른 FlexVol 볼륨을 생성할 수 있습니다. VM 스토리지 정책을 사용하여 정의된 대로 적절한 FlexVol 볼륨에서 가상 머신에 대한 VVol을 자동으로 생성할 수 있습니다. 예를 들어, 성능 제한 및 암호화 또는 FabricPool와 같은 기타 기능에 대한 프로파일을 일반 스토리지 클래스에 생성할 수 있습니다. 나중에 가상 머신의 비즈니스 클래스를 나타내는 vCenter Server에서 VM 스토리지 정책을 생성하고 이름을 기준으로 적절한 스토리지 용량 프로필에 연결할 수 있습니다(예: 운영, 테스트, HR).

VVOL과 함께 사용할 경우 스토리지 성능 프로필도 개별 가상 머신의 스토리지 성능을 설정하고 성능 요구사항을 가장 충족하는 VVOL 데이터 저장소의 FlexVol 볼륨에 배치합니다. 성능에 대한 최소 및/또는 최대 IOPS로 QoS 정책을 지정할 수 있습니다. 처음에 가상 시스템을 프로비저닝할 때 기본 정책을 사용하거나 비즈니스 요구사항이 변경될 경우 나중에 VM 스토리지 정책을 변경할 수 있습니다. 이번 릴리즈의 ONTAP 툴에 대한 기본 스토리지 기능 프로필은 다음과 같습니다.

* AFF_Thick
* FAS_MAX20
* FAS_Default를 선택합니다
* AFF_Default(기본값)
* AFF_계층화
* AFF_암호화됨
* AFF_Encrypted_Tiering을 참조하십시오
* aff_encrypted_min50
* 플래티넘
* 브론즈


그런 다음 vCenter Server는 LUN 또는 볼륨의 스토리지 기능을 해당 LUN 또는 볼륨에 프로비저닝된 데이터 저장소와 연결합니다. 이를 통해 가상 머신의 스토리지 프로필과 일치하는 데이터 저장소에 가상 머신을 프로비저닝하고 데이터 저장소 클러스터의 모든 데이터 저장소에 동일한 스토리지 서비스 수준이 있는지 확인할 수 있습니다.

ONTAP 툴을 사용하면 동일한 VVOL 데이터 저장소에서 다양한 IOPS 요구 사항에 따라 가상 머신의 프로비저닝을 지원하는 새로운 스토리지 기능 프로필로 모든 가상 볼륨(VVol) 데이터 저장소를 구성할 수 있습니다. IOPS 요구 사항이 있는 VM 프로비저닝 워크플로우를 실행하는 동안 모든 VVol 데이터스토어가 호환 가능한 데이터 저장소 목록에 나열됩니다.



== 스토리지 용량 프로파일을 생성 및 편집할 때의 고려 사항

스토리지 용량 프로필을 생성 및 편집할 때 고려해야 할 사항에 대해 알고 있어야 합니다.

* AFF 시스템에서만 최소 IOPS를 구성할 수 있습니다.
* VVOL(가상 볼륨) 데이터 저장소 수준에서 QoS 메트릭을 구성할 수 있습니다.
+
이 기능을 사용하면 가상 데이터 저장소에 프로비저닝된 동일한 가상 머신의 서로 다른 VMDK에 다양한 QoS 메트릭을 할당할 수 있습니다.

* FAS 및 AFFDatastores 모두에 대해 스토리지 용량 프로필을 구성할 수 있습니다.
+
FAS 및 AFF 시스템의 경우 공간 예비 공간이 일반 또는 씬 공간으로 구성할 수 있습니다.

* 스토리지 용량 프로필을 사용하여 데이터 저장소에 대한 암호화를 제공할 수 있습니다.
* 이전 버전의 VMware vSphere용 ONTAP 툴에서 최신 버전의 ONTAP 툴로 업그레이드한 후에는 기존 스토리지 기능 프로파일(7.2 버전 이전에 생성됨)을 수정할 수 없습니다.
+
기존 스토리지 기능 프로필은 이전 버전과의 호환성을 위해 유지됩니다. 기본 템플릿을 사용하지 않는 경우 최신 버전의 ONTAP 툴로 업그레이드하는 동안 스토리지 기능 프로필의 성능과 관련된 새로운 QoS 메트릭 및 계층화 정책을 반영하도록 기존 템플릿이 재정의됩니다.

* 기존 스토리지 기능 프로필을 수정하거나 사용하여 새 가상 데이터 저장소 또는 VM 스토리지 정책을 프로비저닝할 수 없습니다.
* 모든 새 데이터 저장소에 새 스토리지 용량 프로필을 사용해야 합니다.

