---
permalink: configure/reference_set_ipv4_or_ipv6.html 
sidebar: sidebar 
keywords:  
summary: VSC에 추가된 모든 스토리지 시스템에 대해 IPv4 또는 IPv6를 지원하도록 설정할 수 있는 기본 설정 파일 kaminoprefs.xml에 새로운 옵션이 추가되었습니다. 
---
= 기본 설정 파일을 사용하여 IPv4 또는 IPv6를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 설정 파일에는 VMware vSphere 작업을 위한 ONTAP 툴을 제어하는 설정이 포함되어 있습니다. 대부분의 경우 이러한 파일의 설정을 수정할 필요가 없습니다. VSC(가상 스토리지 콘솔)에서 사용되는 기본 설정 파일을 알면 도움이 됩니다.

VSC에는 몇 가지 기본 설정 파일이 있습니다. 이러한 파일에는 VSC에서 다양한 작업을 수행하는 방법을 결정하는 항목 키와 값이 포함되어 있습니다. 다음은 VSC에서 사용하는 몇 가지 기본 설정 파일입니다.

'/opt/netapp/vscserver/etc/kaminoprefs.xml'

'/opt/netapp/vscserver/etc/vsc/vscPreferences.xml'

특정 상황에서 기본 설정 파일을 수정해야 할 수 있습니다. 예를 들어 iSCSI 또는 NFS를 사용하고 서브넷이 ESXi 호스트와 스토리지 시스템 간에 다른 경우 기본 설정 파일을 수정해야 합니다. 기본 설정 파일에서 설정을 수정하지 않으면 VSC에서 데이터 저장소를 마운트할 수 없기 때문에 데이터 저장소 프로비저닝이 실패합니다.

VSC에 추가된 모든 스토리지 시스템에서 IPv4 또는 IPv6를 지원하도록 설정할 수 있는 기본 설정 파일 "kaminoprefs.xml"에 새로운 옵션이 추가되었습니다.

* default.override.option.provision.mount.datastore.address.family` 매개 변수가 데이터 저장소 프로비저닝을 위해 선호되는 데이터 LIF 프로토콜을 설정하기 위해 "kaminoprefs.xml" 기본 설정 파일에 추가되었습니다.
+
이 기본 설정은 VSC에 추가된 모든 스토리지 시스템에 적용됩니다.

* 새 옵션의 값은 IPv4 IPv6 없음.
* 기본적으로 이 값은 "없음"으로 설정됩니다.


|===


| * 값 * | * 설명 * 


 a| 
없음
 a| 
* 프로비저닝은 스토리지 추가에 사용되는 클러스터 또는 SVM 관리 LIF의 유형과 동일한 IPv6 또는 IPv4 주소 유형의 데이터 LIF를 사용하여 수행됩니다.
* SVM에 동일한 IPv6 또는 IPv4 주소 유형의 데이터 LIF가 없으면 다른 유형의 데이터 LIF를 통해 프로비저닝이 수행됩니다(가능한 경우).




 a| 
IPv4
 a| 
* 프로비저닝은 선택한 SVM에서 IPv4 데이터 LIF를 사용하여 수행됩니다.
* SVM에 IPv4 데이터 LIF가 없으면 SVM에서 사용 가능한 경우 IPv6 데이터 LIF를 통해 프로비저닝이 수행됩니다.




 a| 
IPv6
 a| 
* 프로비저닝 은 선택한 SVM에서 IPv6 데이터 LIF를 사용하여 수행됩니다.
* SVM에 IPv6 데이터 LIF가 없으면 SVM에서 사용 가능한 경우 IPv4 데이터 LIF를 통해 프로비저닝이 수행됩니다.


|===