---
permalink: configure/task_register_oncommand_api_services_with_ontap_tools.html 
sidebar: sidebar 
keywords: virtual volume datastores 
summary: 'ONTAP 9.6 이하를 사용하는 경우, VVol 대시보드는 VVol VM 및 데이터 저장소 보고서에 대한 데이터를 얻기 위해 VASA Provider용 OnCommand API Services를 등록한 경우에만 VVol\(VMware Virtual Volumes\) 데이터 저장소 및 가상 머신의 세부 정보를 표시할 수 있습니다.' 
---
= ONTAP 툴을 사용하여 OnCommand API 서비스를 등록합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.6 이하를 사용하는 경우, VASA Provider용 OnCommand API Services를 등록하여 VVol VM 및 데이터 저장소 보고서에 대한 데이터를 얻은 경우에만 VVol 대시보드에서 VVol(VMware Virtual Volumes) 데이터 저장소 및 가상 시스템의 세부 정보를 표시할 수 있습니다.

* 필요한 것 *

NetApp Support 사이트에서 OnCommand API Services 2.1 이상을 다운로드해야 합니다.


NOTE: ONTAP 9.3 이상을 사용하여 SAN VVOL 데이터 저장소 및 가상 머신을 구성한 경우에만 VVol 대시보드에 성능 메트릭이 표시됩니다.

* 단계 *

. ONTAP 도구 홈 페이지에서 * 설정 * 을 클릭합니다.
. 관리 설정 탭에서 * 확장 관리 * 를 클릭합니다.
. OnCommand API 서비스 등록 슬라이더를 사용하여 OnCommand API 서비스를 활성화합니다.
. OnCommand API 서비스의 IP 주소, 서비스 포트 및 자격 증명을 입력합니다.
+
VASA Provider Extensions 관리 대화 상자를 사용하여 다음 사항을 수정할 수도 있습니다.

+
** 자격 증명이 변경된 경우 OnCommand API 서비스 등록을 업데이트하려면
** VVol 대시보드가 더 이상 필요하지 않은 경우 OnCommand API Services의 등록을 취소합니다.
+
VASA Provider에 대한 OnCommand API 서비스 등록을 제거하려면 OnCommand API 서비스 등록 확인란의 선택을 해제해야 합니다.



. 적용 * 을 클릭합니다.
+
ONTAP API 서비스 등록이 완료된 후에만 VVOL 대시보드가 OnCommand 9.6 또는 이전 SAN VVOL 데이터 저장소에 대한 메트릭을 표시합니다.



* 관련 정보 *

https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]
