---
permalink: configure/task_add_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: '스토리지 시스템을 가상 스토리지 콘솔\(VSC\)에 수동으로 추가할 수 있습니다.' 
---
= 스토리지 시스템을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템을 VSC(가상 스토리지 콘솔)에 수동으로 추가할 수 있습니다.


NOTE: ONTAP 클러스터가 SAML이 활성화된 경우 ONTAP와의 통신은 기본 인증을 통해 수행됩니다.

* 이 작업에 대한 정보 *

VSC(가상 스토리지 콘솔)를 시작하거나 * REDiscover All * 옵션을 선택할 때마다 VSC는 사용 가능한 스토리지 시스템을 자동으로 검색합니다.

* 단계 *

. ONTAP 툴 홈 페이지의 옵션 중 하나를 사용하여 스토리지 시스템을 VSC에 추가합니다.
+
** 스토리지 시스템 * > * 추가 * 를 클릭합니다. 또는
** Overview * > * Getting Started * 를 클릭한 다음 Add Storage System 아래의 * add * 버튼을 클릭합니다.


. 스토리지 시스템 추가 * 대화 상자에서 해당 스토리지 시스템의 관리 IP 주소와 자격 증명을 입력합니다.
+
스토리지 시스템을 추가할 때 ONTAP 툴 플러그인과 스토리지 시스템 간의 통신이 상호 인증되어야 합니다.

+
클러스터 또는 SVM의 IPv6 주소를 사용하여 스토리지 시스템을 추가할 수도 있습니다.

+
VSC 스토리지 시스템 페이지에서 스토리지를 추가할 때 스토리지가 있는 vCenter Server 인스턴스를 지정합니다. Add Storage System 대화 상자에는 사용 가능한 vCenter Server 인스턴스의 드롭다운 목록이 제공됩니다. vCenter Server 인스턴스와 이미 연결된 데이터 센터에 스토리지를 추가할 경우 VSC에서 이 옵션을 표시하지 않습니다.

+
참고:

+
** ONTAP 툴 9.12 릴리즈 이상에서 모든 ONTAP 스토리지 시스템 통신은 인증서 기반 인증을 통해 수행됩니다.
** 클라이언트 또는 클러스터 인증서 중 하나가 유효하지 않으면 삭제, 크기 조정 및 마운트와 같은 기존 데이터 저장소 작업이 허용되지 않습니다.
** 클라이언트 또는 클러스터 인증서 중 하나가 유효하지 않은 경우 저장소 확장, 데이터 저장소 마운트 등의 VVOL 데이터 저장소 작업은 허용되지 않습니다.
** 삭제, 스토리지 제거, 속성 편집 등의 작업은 ONTAP 통신이 필요하지 않으므로 허용됩니다.
** SVM 범위 사용자로 스토리지 시스템을 추가하려면 스토리지 시스템 클러스터 관리자가 사용자를 편집하고 인증 방법 * Certificate * 를 애플리케이션 HTTP 및 ONTAPI에 추가해야 합니다.
+
고급 옵션에서 * ONTAP 클러스터 인증서 * 를 업로드하는 방법에는 두 가지가 있습니다.

+
... * 자동으로 가져오기 * - 자동으로 인증서를 가져옵니다.
... * 수동 업로드 * - 인증서가 있는 위치를 수동으로 찾아 인증서를 업로드해야 합니다.




. 필요한 정보를 모두 추가한 후 * 확인 * 을 클릭합니다.
+
클러스터 인증서 승인 팝업이 나타납니다.

. 인증서 세부 정보를 보려면 * 인증서 표시 * 를 클릭합니다. 스토리지 시스템을 추가하려면 * 예 * 를 클릭합니다

