---
permalink: configure/task_provision_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: ONTAP 툴에서 VASA Provider가 활성화된 경우에만 데이터 저장소 용량 할당 마법사를 사용하여 VVOL 데이터 저장소를 프로비저닝할 수 있습니다. 
---
= VVOL 데이터 저장소를 프로비저닝합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 툴에서 VASA Provider가 활성화된 경우에만 데이터 저장소 용량 할당 마법사를 사용하여 VVOL 데이터 저장소를 프로비저닝할 수 있습니다.

* 필요한 것 *

* ESXi가 호스팅되는 모든 네트워크의 서브넷 세부 정보가 Kaminoprefs.xml에 입력되었는지 확인해야 합니다.
+
다른 서브넷에 데이터 저장소 마운트 설정 * 섹션을 참조하십시오.

* 역방향 복제가 성공하려면 소스 사이트와 타겟 사이트 모두에서 데이터 저장소에 유사한 복제 정책 및 스케줄을 구성해야 합니다.


데이터 저장소 프로비저닝 메뉴를 사용하면 데이터 저장소에 대한 스토리지 기능 프로필을 지정할 수 있으므로 일관된 SLO(서비스 수준 목표)를 지정하고 프로비저닝 프로세스를 간소화할 수 있습니다. VASA Provider를 설정한 경우에만 스토리지 용량 프로파일을 지정할 수 있습니다.

백업 저장소로 사용되는 FlexVol 볼륨은 ONTAP 9.5 이상을 실행하는 경우에만 VVol 대시보드에 표시됩니다. vCenter Server New Datastore 마법사를 사용하여 VVol 데이터 저장소를 프로비저닝해서는 안 됩니다.

* VVOL 데이터 저장소를 생성하려면 클러스터 자격 증명을 사용해야 합니다.
+
SVM 자격 증명을 사용하여 VVol 데이터 저장소를 생성할 수 없습니다.

* VASA Provider는 프로토콜의 VVol 데이터 저장소에서 다른 프로토콜을 사용하는 다른 데이터 저장소로 호스팅되는 가상 머신의 클론을 지원하지 않습니다.
* 소스 사이트와 대상 사이트 모두에서 클러스터 페어링 및 SVM 페어링을 완료해야 합니다.


* 이 작업에 대한 정보 *


NOTE: ONTAP 도구의 9.10 릴리스는 모든 ASA(SAN 어레이) 유형 ONTAP 9.9.1 이상의 스토리지 플랫폼에 대해 vmdk 크기가 16TB를 초과하는 VVol 데이터 저장소를 생성할 수 있도록 지원합니다.

* 단계 *

. vSphere Client 홈 페이지에서 * 호스트 및 클러스터 * 를 클릭합니다.
. 탐색 창에서 데이터 저장소를 프로비저닝할 데이터 센터를 선택합니다.
. 데이터 저장소를 마운트할 호스트를 지정합니다.
+
|===


| * 데이터 저장소를... * 에서 사용할 수 있도록 설정합니다 | 이 작업을 수행하세요. * 


 a| 
데이터 센터에 있는 모든 호스트
 a| 
데이터 센터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp VSC * > * Provision Datastore * 를 선택합니다.



 a| 
클러스터의 모든 호스트
 a| 
클러스터를 마우스 오른쪽 버튼으로 클릭한 다음 * NetApp VSC * > * Provision Datastore * 를 선택합니다.



 a| 
단일 호스트
 a| 
호스트를 마우스 오른쪽 버튼으로 클릭한 다음 * NetApp VSC * > * Provision Datastore * 를 선택합니다.

|===
. New Datastore 대화 상자의 필드를 입력하여 데이터 저장소를 생성합니다.
+
대화 상자의 대부분의 필드는 설명이 필요 없습니다. 다음 표에서는 안내가 필요할 수 있는 일부 필드에 대해 설명합니다.

+
|===


| * 섹션 * | * 설명 * 


 a| 
일반
 a| 
New Datastore 대화 상자의 General 섹션에서는 새 데이터 저장소의 위치, 이름, 설명, 유형 및 프로토콜을 입력하는 옵션을 제공합니다. VVOL 데이터 저장소 유형은 VVol 데이터 저장소를 구성하는 데 사용됩니다.


NOTE: VVOL 복제를 위해 iSCSI VVOL 데이터 저장소를 프로비저닝하고 타겟 사이트에서 VVol 데이터 저장소를 생성하기 전에 SnapMirror 업데이트 및 클러스터 재검색을 수행해야 합니다.



 a| 
수행할 수 있습니다
 a| 
이 섹션에서는 VVOL 데이터 저장소에 복제를 활성화할지 또는 비활성화할지를 선택할 수 있습니다. 이 릴리즈에서는 비동기 유형 복제 프로파일만 허용됩니다. 그런 다음 나열된 스토리지 용량 프로필을 하나 이상 선택할 수 있습니다. 페어링된 * 스토리지 시스템 * 및 * 스토리지 VM * 의 시스템 권장 값이 자동으로 채워집니다. 권장 값은 ONTAP에서 페어링된 경우에만 채워집니다. 필요한 경우 이러한 값을 수정할 수 있습니다.

* 참고: * ONTAP에서 FlexVol 볼륨을 생성하는 동안 스토리지 용량 프로필에서 선택하려는 속성을 사용하여 생성해야 합니다. 읽기 쓰기 및 데이터 보호 FlexVol 볼륨은 모두 유사한 특성을 가져야 합니다.

FlexVol 볼륨이 생성되고 ONTAP에서 SnapMirror를 초기화한 후에는 VSC에서 스토리지 재검색을 실행하여 새 볼륨을 볼 수 있어야 합니다.



 a| 
스토리지 특성
 a| 
기존 목록에서 SnapMirror와 필요한 FlexVol 볼륨의 일정을 선택해야 합니다. 이 스케줄은 VM 스토리지 정책 페이지에서 선택한 스케줄과 비슷해야 합니다. 사용자는 목록에 있는 SnapMirror와 함께 ONTAP에 FlexVol 볼륨을 생성해야 합니다. Default storage capability profile * 옵션을 사용하여 VVol 생성에 사용할 기본 저장소 기능 프로파일을 선택할 수 있습니다. 기본적으로 모든 볼륨은 최대 자동 행 크기로 120%로 설정되고 기본 스냅샷은 이러한 볼륨에서 활성화됩니다.

* 참고: *

** VVOL 데이터 저장소의 일부인 FlexVol 볼륨은 기존 크기보다 축소될 수 없지만 최대 120% 성장할 수 있습니다. 이 FlexVol 볼륨에서 기본 스냅샷이 활성화됩니다.
** 생성해야 하는 FlexVol 볼륨의 최소 크기는 5GB입니다.


|===
. 요약 섹션에서 ** 완료**를 클릭합니다.


결과 *

VVol 데이터 저장소가 구성되면 백엔드에서 복제 그룹이 생성됩니다.

* 관련 정보 *

link:../manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html["VVOL 대시보드를 사용하여 성능 데이터를 분석합니다"]
