---
permalink: configure/task_enable_datastore_mounting_across_different_subnets.html 
sidebar: sidebar 
keywords:  
summary: 'iSCSI 또는 NFS를 사용하고 서브넷이 ESXi 호스트와 스토리지 시스템 간에 서로 다른 경우 VMware vSphere 기본 설정 파일에 대한 ONTAP 툴을 수정해야 합니다. 기본 설정 파일을 수정하지 않으면 가상 스토리지 콘솔\(VSC\)에서 데이터 저장소를 마운트할 수 없기 때문에 데이터 저장소 프로비저닝이 실패합니다.' 
---
= 서로 다른 서브넷에 데이터 저장소 마운트를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 또는 NFS를 사용하고 서브넷이 ESXi 호스트와 스토리지 시스템 간에 서로 다른 경우 VMware vSphere 기본 설정 파일에 대한 ONTAP 툴을 수정해야 합니다. 기본 설정 파일을 수정하지 않으면 VSC(가상 스토리지 콘솔)에서 데이터 저장소를 마운트할 수 없기 때문에 데이터 저장소 프로비저닝이 실패합니다.

* 이 작업에 대한 정보 *

데이터 저장소 프로비저닝이 실패하면 VSC에서 다음 오류 메시지를 기록합니다.

"계속할 수 없습니다. 컨트롤러의 커널 IP 주소 및 주소를 상호 참조할 때 IP 주소를 찾을 수 없습니다.

NFS 마운트 볼륨과 일치하는 네트워크를 찾을 수 없습니다

* 단계 *

. vCenter Server 인스턴스에 로그인합니다.
. 통합 어플라이언스 가상 머신을 사용하여 유지보수 콘솔을 시작합니다.
+
link:reference_maintenance_console_of_ontap_tools_for_vmware_vsphere.html["VMware vSphere용 ONTAP 툴의 유지 관리 콘솔입니다"]

. 지원 및 진단 옵션에 액세스하려면 '4'를 입력하십시오.
. Access Diagnostic Shell 옵션에 액세스하려면 "2"를 입력합니다.
. kaminoprefs.xml을 업데이트하려면 vi/opt/netapp/vscserver/etc/kaminoprefs.xml을 입력하십시오.
. kaminoprefs.xml 파일을 업데이트합니다.
+
|===


| * 를 사용하는 경우... * | 이 작업을 수행하세요. * 


 a| 
iSCSI
 a| 
항목 키 ddefault.allow.iscsi.mount.networks` 값을 모두 에서 ESXi 호스트 네트워크 값으로 변경합니다.



 a| 
NFS 를 참조하십시오
 a| 
항목 키 ddefault.allow.nfs.mount.networks` 값을 모두 에서 ESXi 호스트 네트워크 값으로 변경합니다.

|===
+
기본 설정 파일에는 이러한 입력 키에 대한 샘플 값이 포함되어 있습니다.

+

NOTE: 모든 네트워크가 의미하는 것은 아닙니다. ""모두" 값을 사용하면 호스트와 스토리지 시스템 간의 일치하는 모든 네트워크를 데이터 저장소를 마운트하는 데 사용할 수 있습니다. 호스트 네트워크를 지정할 때 지정된 서브넷에서만 마운트를 활성화할 수 있습니다.

. kaminoprefs.xml 파일을 저장하고 닫습니다.

