---
permalink: configure/task_enable_vasa_provider_for_configuring_virtual_datastores.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP 툴에는 기본적으로 VASA 공급자 기능이 설정되어 있습니다. 각 VVol 데이터스토어에 필요한 스토리지 기능 프로필을 사용하여 VVol(VMware Virtual Volumes)\) 데이터 저장소를 구성할 수 있습니다.' 
---
= 가상 데이터 저장소를 구성하기 위해 VASA Provider를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴에는 기본적으로 VASA 공급자 기능이 설정되어 있습니다. 각 VVol 데이터 저장소에 필요한 스토리지 기능 프로필을 사용하여 VVol(VMware Virtual Volumes) 데이터 저장소를 구성할 수 있습니다.

* 필요한 것 *

* vCenter Server 인스턴스를 설정하고 ESXi를 구성해야 합니다.
* ONTAP 툴을 구축해야 합니다.


* 이 작업에 대한 정보 *

ONTAP 툴의 9.7.1 릴리즈로 업그레이드하기 전에 VASA 공급자 기능이 비활성화된 경우 업그레이드 후에도 VASA 공급자 기능이 비활성화된 상태로 유지됩니다. 이 릴리즈를 사용하면 VVOL 데이터 저장소에 대한 VVol 복제 기능을 활성화할 수 있습니다.

* 단계 *

. VMware vSphere의 웹 사용자 인터페이스에 로그인합니다.
. vSphere 클라이언트에서 * 메뉴 * > * NetApp ONTAP 툴 * 을 선택합니다.
. 설정 * 을 클릭합니다.
. 관리 설정 탭에서 * 기능 관리 * 를 클릭합니다.
. Manage Capabilities 대화 상자에서 사용할 VASA Provider 확장을 선택합니다.
. VVOL 데이터 저장소의 복제 기능을 사용하려면 * VVol 복제 활성화 * 전환 버튼을 사용합니다.
. ONTAP 도구의 IP 주소와 관리자 암호를 입력한 다음 * 적용 * 을 클릭합니다.
+

NOTE: VASA Provider 확장을 설정한 후에도 VASA Provider 상태가 ""오프라인""으로 표시되면 /var/log/vmware/vmware-SPS/sps.log 파일에서 VASA Provider의 연결 오류를 확인하거나 ""VMware-SPS" 서비스를 다시 시작하십시오.



* 관련 정보 *

https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"]
