---
permalink: manage/concept_virtual_storage_console_reports.html 
sidebar: sidebar 
keywords:  
summary: ONTAP 툴 콘솔 보고서 메뉴를 사용하여 특정 vCenter Server에서 선택한 VSC 인스턴스에서 관리하는 모든 데이터 저장소에 대한 사전 정의된 보고서를 볼 수 있습니다. 보고서 정렬 및 내보내기 등의 작업을 수행할 수 있습니다. 
---
= ONTAP 툴 데이터 저장소 및 VVol 보고서 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 툴 콘솔 * 보고서 * 메뉴를 사용하면 특정 vCenter Server에서 선택한 VSC 인스턴스에서 관리하는 모든 데이터 저장소에 대해 미리 정의된 보고서를 볼 수 있습니다. 보고서 정렬 및 내보내기 등의 작업을 수행할 수 있습니다.

보고서는 vCenter Server에서 데이터 저장소 및 가상 시스템의 잠재적 문제를 검토하고 식별할 수 있도록 데이터 저장소 및 가상 시스템에 대한 자세한 정보를 표시합니다

보고서를 보고, 정렬하고, 내보낼 수 있습니다.

VSC(가상 스토리지 콘솔)는 다음과 같은 사전 정의 보고서를 제공합니다.

* 데이터 저장소 보고서
* 가상 시스템 보고서
* VVOL 데이터 저장소 보고서
* VVOL 가상 머신 보고서
* 로그 무결성 보고서




== 데이터 저장소 보고서

데이터 저장소 보고서는 기존 데이터 저장소 및 이러한 데이터 저장소에 생성된 가상 머신에 대한 자세한 정보를 제공합니다.

기존 대시보드를 사용하면 vCenter Server의 데이터 저장소 및 가상 시스템과 관련된 잠재적인 문제를 검토하고 식별할 수 있습니다. 보고서를 보고, 정렬하고, 내보낼 수 있습니다. 기존 데이터 저장소 및 가상 머신 보고서의 데이터는 vCenter Server에서 제공합니다. 하지만 FlexGroup에서 지원하는 데이터 저장소를 지원하기 때문에 지연 시간, 처리량, IOPS와 같은 일부 메트릭을 ONTAP에서 얻을 수 있습니다.


NOTE: 직접 스토리지 가상 시스템(SVM)에 구성된 FlexGroup 데이터 저장소에는 파일 모니터링이 지원되지 않습니다.

데이터 저장소는 다음과 같은 사전 정의된 보고서를 제공합니다.

* 데이터 저장소 보고서
* 가상 시스템 보고서


* 데이터 저장소 보고서 *

Datastore Report 메뉴에는 데이터 저장소에 대한 다음 매개 변수에 대한 정보가 제공됩니다.

* 데이터 저장소의 이름입니다
* 데이터 저장소 유형: NFS 및 VMFS
* 볼륨 스타일
+
볼륨 스타일은 FlexVol 볼륨 또는 FlexGroup 볼륨일 수 있습니다.

* 여유 공간
* 사용된 공간
* 총 공간
* 사용된 공간의 비율입니다
* 사용 가능한 공간의 비율입니다
* IOPS
+
보고서에 데이터 저장소의 IOPS가 표시됩니다.

* 지연 시간
+
이 보고서에는 데이터 저장소의 지연 시간 정보가 표시됩니다.

+
보고서가 생성된 시간을 확인할 수도 있습니다. Datastore Report 메뉴를 사용하면 필요에 따라 보고서를 구성한 다음 * Export to CSV * 버튼을 사용하여 조직화된 보고서를 내보낼 수 있습니다. 보고서의 데이터 저장소 이름은 데이터 저장소 성능 메트릭을 볼 수 있는 선택한 데이터 저장소의 Monitor 탭으로 이동하는 링크입니다.



* 가상 머신 보고서 *

Virtual Machine Report 메뉴는 선택한 vCenter Server에 대해 VSC에서 프로비저닝한 데이터 저장소를 사용하는 모든 가상 머신의 성능 메트릭을 제공합니다. 가상 머신 보고서에 표시되는 가상 머신 메트릭은 기존 데이터 저장소의 가상 머신에 대해 30분마다 수집되는 기간별 데이터입니다. "마지막 새로 고침 시간" 및 "다음 새로 고침 시간"이 테이블에 추가되어 데이터 수집 시기 및 다음 데이터 수집 시기에 대한 세부 정보를 제공합니다.

* 가상 머신의 이름입니다
* 데이터 저장소 이름입니다
* 볼륨 스타일
+
볼륨 스타일은 FlexVol 볼륨 또는 FlexGroup 볼륨일 수 있습니다.

* 출처
+
가상 머신에 대한 세부 정보를 수집하는 소스는 ONTAP 또는 vCenter Server가 될 수 있습니다.

* 지연 시간
+
이 보고서에는 가상 머신과 연결된 모든 데이터 저장소에서 가상 머신에 대한 지연 시간이 표시됩니다.

* IOPS
* 처리량
* 약속된 용량
+
보고서에는 가상 머신에 대해 커밋된 용량 값이 표시됩니다.

* 호스트
+
이 보고서에는 가상 머신을 사용할 수 있는 호스트 시스템이 표시됩니다.

* 가동 시간
+
이 보고서에는 가상 머신의 전원이 켜져 있고 ESXi 호스트에서 사용할 수 있는 시간이 표시됩니다.

* 전원 상태입니다
+
이 보고서는 가상 머신의 전원이 켜져 있는지 또는 전원이 꺼져 있는지 여부를 표시합니다.



보고서의 각 가상 머신 이름은 선택한 가상 머신의 Monitor 탭에 대한 링크입니다. 요구 사항에 따라 가상 머신 보고서를 정렬하고 보고서를 .csv 파일로 내보내고 보고서를 로컬 시스템에 저장할 수 있습니다. 보고서의 타임 스탬프도 저장된 보고서에 추가됩니다.

FlexGroup 볼륨이 지원하는 가상 머신의 경우 새 가상 머신의 전원을 켜면 ONTAP에서 모니터링할 파일이 등록됩니다. 지연 시간, 처리량 및 IOPS에 대한 기간별 메트릭은 ONTAP에서 VM 보고서에 액세스할 때 얻어집니다.



== VVOL 보고서

VVOL 보고서는 VMware 가상 볼륨(VVol) 데이터 저장소 및 해당 데이터 저장소에 생성된 가상 머신에 대한 자세한 정보를 표시합니다. VVol 대시보드를 사용하면 vCenter Server에서 VVOL 데이터 저장소 및 가상 머신과 관련된 잠재적인 문제를 검토하고 식별할 수 있습니다.

보고서를 보고, 구성하고, 내보낼 수 있습니다. ONTAP는 VVOL 데이터 저장소 및 가상 머신 보고서에 대한 데이터를 제공합니다.

VVOL은 사전 스캔 보고서를 다음과 같이 제공합니다.

* VVOL 데이터 저장소 보고서
* Vvols VM 보고서


* VVOL 데이터 저장소 보고서 *

VVol Datastore Report(VVol 데이터스토어 보고서) 메뉴는 데이터스토어에 대한 다음 매개변수에 대한 정보를 제공합니다.

* VVol 데이터스토어 이름입니다
* 여유 공간
* 사용된 공간
* 총 공간
* 사용된 공간의 비율입니다
* 사용 가능한 공간의 비율입니다
* IOPS
* 지연 시간 성능 메트릭은 ONTAP 9.8 이상의 NFS 기반 VVol 데이터 저장소에 사용할 수 있습니다. 보고서가 생성된 시간을 확인할 수도 있습니다. VVol Datastore Report(VVol 데이터스토어 보고서) 메뉴를 사용하면 필요에 따라 보고서를 구성한 다음 * Export to CSV *(CSV로 내보내기) 버튼을 사용하여 조직화된 보고서를 내보낼 수 있습니다. 보고서의 각 SAN VVol 데이터 저장소 이름은 선택한 SAN VVol 데이터 저장소의 Monitor 탭으로 이동하는 링크입니다. 이 탭에서 성능 메트릭을 보는 데 사용할 수 있습니다.


* VVOL 가상 머신 보고서 *

VVol Virtual Machine Summary Report(VVol 가상 머신 요약 보고서) 메뉴는 선택한 vCenter Server에 대해 VASA Provider for ONTAP가 프로비저닝한 SAN VVol 데이터 저장소를 사용하는 모든 가상 머신의 성능 메트릭을 제공합니다. VM 보고서에 표시되는 가상 머신 메트릭은 VVOL 데이터 저장소의 가상 머신에 대해 10분마다 수집되는 기간별 데이터입니다. "마지막 새로 고침 시간" 및 "다음 새로 고침 시간"이 테이블에 추가되어 데이터 수집 시기 및 다음 데이터 수집 시기에 대한 정보를 제공합니다.

* 가상 머신의 이름입니다
* 약속된 용량
* 가동 시간
* IOPS
* 처리량
+
이 보고서는 가상 머신의 전원이 켜져 있는지 또는 전원이 꺼져 있는지 여부를 표시합니다.

* 논리적 공간입니다
* 호스트
* 전원 상태입니다
* 지연 시간
+
이 보고서는 가상 머신과 연결된 모든 VVol 데이터스토어의 가상 머신 지연 시간을 표시합니다.



보고서의 각 가상 머신 이름은 선택한 가상 머신의 Monitor 탭에 대한 링크입니다. 필요에 따라 가상 머신 보고서를 구성하고 보고서를 '.csv' 형식으로 내보낸 다음 보고서를 로컬 시스템에 저장할 수 있습니다. 보고서의 타임 스탬프가 저장된 보고서에 추가됩니다.

* 로그 무결성 보고서 *

로그 무결성 보고서에는 파일 무결성 상태가 표시됩니다. 로그 무결성은 예약된 간격으로 검사되고 보고서는 로그 무결성 보고서 탭에 표시됩니다. 또한 롤오버되는 여러 감사 파일의 상태도 제공합니다.

사용 가능한 로그 파일 상태는 다음과 같습니다.

* Active(활성): 로그가 기록되는 현재 활성 파일을 나타냅니다.
* Normal(일반): 아카이브 파일이 변조되거나 삭제되지 않았음을 나타냅니다.
* 변경: 파일이 보관 후 수정되었음을 나타냅니다
* ROLLOVER_DELETE: log4j 보존 정책의 일부로 파일이 삭제되었음을 나타냅니다.
* Unexpected_delete: 파일이 수동으로 삭제되었음을 나타냅니다.


VMware vSphere용 ONTAP 툴은 다음에 대한 감사 로깅을 생성합니다.

* VSC 서비스
+
vscservice의 감사 로그 위치: _/opt/netapp/vscservice/vsc-audit.log_. 로그 무결성 보고서의 다음 매개 변수는 _/opt/netapp/vscserver/etc/log4j2.properties_ 파일에서 변경할 수 있습니다.

+
** 롤오버의 최대 로그 크기입니다.
** 보존 정책, 이 매개 변수의 기본값은 10개 파일입니다.
** 파일 크기, 이 매개 변수의 기본값은 파일이 보관되기 10MB입니다. 새 값을 적용하려면 서비스를 다시 시작해야 합니다.


* VP 서비스
+
VP 서비스의 감사 로그 위치: _/opt/netapp/vpservice/vp-audit.log_vp 감사 로그는 file_/opt/netapp/vpserver/conf/log4j2.properties_ 에서 수정할 수 있습니다. 새 값을 적용하려면 서비스를 다시 시작해야 합니다.

* 유지보수 명령
+
유지보수 서비스의 감사 로그 위치: _/opt/netapp/vscservice/maint-audit.log_maint 로그 파일은 _/opt/netapp/vscserver/etc/maint_logger.properties_ 파일에서 수정할 수 있습니다. 기본값을 변경하면 새 값이 적용되도록 서버를 다시 시작합니다.



스케줄러는 정기적으로 감사 로그를 확인하도록 설정할 수 있습니다. 스케줄러의 기본값은 1일입니다. 값은 _/opt/netapp/vscserver/etc/maint_logger.properties_ 파일에서 변경할 수 있습니다.
