---
permalink: manage/task_resize_datastores.html 
sidebar: sidebar 
keywords:  
summary: 데이터 저장소의 크기를 조정하면 가상 머신 파일의 스토리지를 늘리거나 줄일 수 있습니다. 인프라스트럭처 요구 사항이 변경됨에 따라 데이터 저장소의 크기를 변경해야 할 수 있습니다. 
---
= 데이터 저장소 크기 조정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 저장소의 크기를 조정하면 가상 머신 파일의 스토리지를 늘리거나 줄일 수 있습니다. 인프라스트럭처 요구 사항이 변경됨에 따라 데이터 저장소의 크기를 변경해야 할 수 있습니다.

* 이 작업에 대한 정보 *

ONTAP 툴이 VMFS 데이터 저장소의 크기를 조정할 때 포함된 볼륨의 크기를 조정하도록 하려면 VMFS 데이터 저장소를 처음 프로비저닝할 때 Storage attributes 섹션의 * Use existing volume * 옵션을 사용하지 말고 대신 각 데이터 저장소에 대한 새 볼륨을 자동으로 생성하도록 해야 합니다.

NFS 데이터 저장소의 크기를 늘리거나 줄일 수 있지만 VMFS 데이터 저장소의 경우 크기를 늘릴 수만 있습니다. 자동 확장 및 축소 옵션이 있는 FlexGroup 데이터 저장소에도 데이터 저장소 크기 조정이 지원됩니다. VVOL 데이터 저장소의 일부인 기존 데이터 저장소 및 FlexVol 볼륨의 일부인 FlexGroup는 기존 크기보다 축소될 수 없지만 최대 120% 성장할 수 있습니다. 이러한 FlexGroup 및 FlexVol 볼륨에서 기본 스냅샷이 활성화됩니다.


NOTE: ONTAP 9.9.1 이상이 설치된 모든 SAN 어레이(ASA) 유형 스토리지 플랫폼을 사용하는 경우, vmdk 크기가 16TB를 초과하는 VVol 데이터 저장소를 만들 수 있습니다.

* 단계 *

. vSphere Client 홈 페이지에서 * 호스트 및 클러스터 * 를 클릭합니다.
. 탐색 창에서 데이터 저장소가 포함된 데이터 센터를 선택합니다.
. 데이터 저장소를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Resize non-vVols datastore * 를 선택합니다.
. 크기 조정 대화 상자에서 데이터 저장소의 새 크기를 지정한 다음 * 확인 * 을 클릭합니다.
+
스토리지 시스템 메뉴에서 * 모두 다시 검색 * 옵션을 실행하여 스토리지 시스템 및 대시보드에서 스토리지 목록을 수동으로 업데이트하거나 다음 예정된 새로 고침을 기다릴 수 있습니다.


