---
permalink: manage/task_monitor_datastores_using_the_traditional_dashboard.html 
sidebar: sidebar 
keywords:  
summary: ONTAP 툴의 기존 대시보드를 사용하여 기존 데이터 저장소와 가상 머신을 모니터링할 수 있습니다. 대시보드 데이터를 사용하여 데이터 저장소 사용량을 분석하고 수정 조치를 취하여 가상 머신이 공간 관련 제약으로 실행되지 않도록 방지할 수 있습니다. 
---
= 기존 대시보드를 사용하여 성능 데이터를 분석합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 툴의 기존 대시보드를 사용하여 기존 데이터 저장소와 가상 머신을 모니터링할 수 있습니다. 대시보드 데이터를 사용하여 데이터 저장소 사용량을 분석하고 수정 조치를 취하여 가상 머신이 공간 관련 제약으로 실행되지 않도록 방지할 수 있습니다.

* 필요한 것 *

스토리지 I/O 제어 구성 대화 상자에서 * 스토리지 I/O 제어 활성화 및 통계 수집 * 또는 * 스토리지 I/O 제어 비활성화를 선택해야 하지만 통계 수집 * 옵션을 활성화해야 합니다. VMware의 Enterprise Plus 라이센스가 있는 경우에만 스토리지 I/O 제어를 활성화할 수 있습니다.

https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.resmgmt.doc/GUID-BB5D9BAB-9E0E-4204-A76A-54634CD8AD51.html["VMware vSphere 설명서: 스토리지 입출력 제어 설정"]

기존 대시보드에는 vCenter Server에서 얻은 IOPS, 공간 활용, 지연 시간 및 커밋된 용량 메트릭이 표시됩니다. ONTAP는 기존 대시보드에 애그리게이트 공간 절약 메트릭을 제공합니다. 특정 애그리게이트의 공간 절약 효과를 볼 수 있습니다. 이러한 성능 매개 변수를 사용하여 가상 환경의 성능 병목 현상을 파악하고 수정 조치를 취하여 문제를 해결할 수 있습니다.


NOTE: 직접 스토리지 가상 시스템(SVM)에 구성된 FlexGroup 데이터 저장소에는 파일 모니터링이 지원되지 않습니다.

ONTAP 툴의 기존 대시보드를 사용하면 NFS 데이터 저장소 또는 VMFS 데이터 저장소를 볼 수 있습니다. 데이터 저장소를 클릭하여 vCenter Server 인스턴스에서 제공하는 데이터 저장소 세부 정보 보기로 이동하여 vCenter Server의 데이터 저장소 문제를 확인하고 해결할 수 있습니다.

* 단계 *

. vSphere Client 홈 페이지에서 * ONTAP tools for VMware vSphere * 를 클릭합니다.
. vCenter Server 드롭다운 메뉴를 사용하여 필요한 vCenter Server를 선택하여 데이터 저장소를 표시합니다.
. 기존 대시보드 * 를 클릭합니다.
+
데이터 저장소 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server 인스턴스에서 VSC에 의해 관리되는 성능 메트릭과 함께 기존 데이터 저장소의 수
** 수정할 수 있는 리소스 사용 및 성능 매개 변수를 기준으로 상위 5개 데이터 저장소 필요 시 사용된 공간, IOPS 또는 지연 시간과 필요한 순서대로 데이터 저장소 목록을 변경할 수 있습니다.


+
가상 시스템 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server에서 NetApp 데이터 저장소를 사용하는 가상 머신의 수입니다
** 커밋된 용량, 지연 시간, IOPS, 처리량 및 가동 시간을 기반으로 한 상위 5개 가상 머신
+
가상 시스템 포틀릿의 IOPS 및 처리량 데이터는 FlexGroup 백업 볼륨에서 생성된 데이터스토어에 대해서만 사용할 수 있습니다.




