---
permalink: manage/task_set_default_credentials_for_storage_systems.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴을 사용하여 vCenter Server의 스토리지 시스템에 대한 기본 자격 증명을 설정할 수 있습니다. 
---
= 스토리지 시스템에 대한 기본 자격 증명을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴을 사용하여 vCenter Server의 스토리지 시스템에 대한 기본 자격 증명을 설정할 수 있습니다.

* 필요한 것 *

기본 자격 증명을 생성하는 데 사용할 vCenter Server를 선택해야 합니다.

* 이 작업에 대한 정보 *

스토리지 시스템에 대한 기본 자격 증명을 설정하는 경우 ONTAP 툴에서 이러한 자격 증명을 사용하여 ONTAP 툴이 방금 검색한 스토리지 시스템에 로그인합니다. 기본 자격 증명이 작동하지 않는 경우 스토리지 시스템에 수동으로 로그인해야 합니다. ONTAP 툴 및 SRA를 통해 클러스터 레벨 또는 SVM 레벨에서 스토리지 시스템 자격 증명을 추가할 수 있습니다. 그러나 VASA Provider는 클러스터 레벨 자격 증명에서만 작동합니다.

* 단계 *

. ONTAP 도구 홈 페이지에서 * 설정 * > * 관리 설정 * > * 스토리지 시스템의 기본 자격 증명 구성 * 을 클릭합니다.
. 스토리지 시스템 기본 자격 증명 대화 상자에서 스토리지 시스템의 사용자 이름과 암호를 입력합니다.
+
스토리지 컨트롤러 자격 증명은 사용자 이름 및 암호 쌍에 따라 ONTAP에 할당됩니다. 스토리지 컨트롤러 자격 증명은 관리자 계정 또는 RBAC(역할 기반 액세스 제어)를 사용하는 사용자 지정 계정일 수 있습니다.

+
ONTAP 툴을 사용하여 스토리지 컨트롤러의 사용자 이름 및 암호 쌍에 연결된 역할을 변경할 수는 없습니다. ONTAP 도구에 사용할 새 ONTAP 사용자 역할을 수정하거나 작성하려면 시스템 관리자를 사용하십시오.

+
를 참조하십시오 link:..configure/task_configure_user_role_and_privileges.html["사용자 역할 및 권한을 구성합니다"]VMware vSphere용 _ ONTAP 툴 설명서 _ 의 섹션.

. 기본 자격 증명을 저장하려면 * 확인 * 을 클릭합니다.


스토리지 시스템이 보고되었기 때문에 스토리지 시스템 자격 증명을 업데이트한 경우 `Authentication Failure` 상태, 스토리지 시스템 페이지에서 사용할 수 있는 * 모두 다시 검색 * 옵션을 클릭해야 합니다. 이렇게 하면 ONTAP 툴에서 새로운 자격 증명을 사용하여 스토리지 시스템에 연결을 시도합니다.
