---
permalink: manage/task_monitor_vvols_datastores_and_virtual_machines_using_vvols_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 'ONTAP 도구의 VVol 대시보드를 사용하여 선택한 매개 변수를 기반으로 vCenter Server에서 성능을 모니터링하고 상위 5개의 SAN 및 NAS VVol(VMware Virtual Volumes) 데이터 저장소를 볼 수 있습니다.' 
---
= VVOL 대시보드를 사용하여 성능 데이터를 분석합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 툴의 VVol 대시보드를 사용하여 선택한 매개 변수를 기반으로 vCenter Server에서 성능을 모니터링하고 상위 5개의 SAN 및 NAS VVol(VMware Virtual Volumes) 데이터 저장소를 볼 수 있습니다.

* 필요한 것 *

* ONTAP 9.6 이하를 사용하는 경우 OnCommand API 서비스 2.1 이상을 활성화해야 합니다.
+
OnCommand 9.7 이상을 위한 SAN VVOL 데이터 저장소 또는 SAN VVol VM 데이터 저장소 보고서의 세부 정보를 가져오기 위해 VASA Provider에 ONTAP API Services를 등록할 필요는 없습니다.

+
https://mysupport.netapp.com/site/global/dashboard[]

* 스토리지 시스템에 ONTAP 9.3 이상을 사용해야 합니다.


ONTAP에서 제공하는 IOPS 데이터는 반올림되어 VVOL 대시보드에 표시됩니다. ONTAP에서 제공하는 실제 IOPS 값과 VVOL 대시보드에 표시되는 IOPS 값이 다를 수 있습니다. ONTAP 툴은 NFS 기반 VVOL 데이터 저장소의 성능을 모니터링합니다.


NOTE: OnCommand API 서비스를 처음으로 등록하는 경우, SAN VVOL 데이터 저장소의 모든 성능 메트릭 데이터를 15~30분 후에만 VVol 대시보드에서 볼 수 있습니다.

* VVol 대시보드 데이터는 10분 간격으로 주기적으로 갱신됩니다.
* vCenter Server 인스턴스에서 스토리지 시스템을 추가, 수정 또는 삭제한 경우, 일정 기간 동안 VVol 대시보드의 데이터가 변경되지 않을 수 있습니다.
+
이는 OnCommand API 서비스가 ONTAP에서 업데이트된 메트릭을 얻는 데 시간이 오래 걸리기 때문입니다.

* VVol 대시보드의 Overview(개요) 포틀릿에 표시되는 Total IOPS 값은 Read IOPS 값과 Write IOPS 값의 누적 값이 아닙니다.
+
읽기 IOPS, 쓰기 IOPS, 총 IOPS는 OnCommand API 서비스에서 제공하는 별도의 메트릭입니다. OnCommand API Services에서 제공하는 총 IOPS 값과 누적 IOPS 값(읽기 IOPS 값 + 쓰기 IOPS 값) 사이에 차이가 있는 경우, VVOL 대시보드의 IOPS 값에서도 동일한 차이가 관찰됩니다.

* ONTAP 9.8 이상에서 프로비저닝된 NFS 기반 데이터 VVOL은 성능 모니터링을 위해 VVOL 대시보드에 자동으로 등록됩니다.


* 단계 *

. vSphere Client 홈 페이지에서 * ONTAP tools * 를 클릭합니다.
. vCenter Server * 드롭다운 메뉴를 사용하여 필요한 vCenter Server를 선택하여 데이터 저장소를 표시합니다.
. VVOL 대시보드 * 를 클릭합니다.
+
데이터 저장소 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server 인스턴스에서 VASA Provider가 관리하는 VVol 데이터 저장소의 수입니다
** 리소스 사용량 및 성능 매개 변수를 기준으로 상위 5개의 VVOL 데이터 저장소 활용 공간, IOPS 또는 지연 시간과 필요한 순서에 따라 데이터 저장소 목록을 변경할 수 있습니다.


. 가상 머신 포틀릿을 사용하여 가상 머신의 세부 정보를 봅니다.
+
가상 시스템 포틀릿은 다음과 같은 세부 정보를 제공합니다.

+
** vCenter Server에서 ONTAP 데이터 저장소를 사용하는 가상 머신의 수입니다
** IOPS, 지연 시간, 처리량, 약정 용량, 가동 시간, 및 논리 공간 - 상위 5개 가상 시스템이 VVol 대시보드에 나열되는 방법을 사용자 지정할 수 있습니다.






== VVol 대시보드 데이터 요구 사항

VVOL(VMware 가상 볼륨) 데이터 저장소 및 가상 머신의 동적 세부 정보를 표시하려면 VVOL 대시보드의 몇 가지 중요한 요구사항을 확인해야 합니다.

다음 표는 VVol 대시보드에 프로비저닝된 SAN VVol 데이터스토어 및 가상 시스템의 성능 메트릭이 표시되지 않는지 확인해야 할 사항에 대한 개요를 제공합니다.

|===


| * 고려 사항 * | * 설명 * 


 a| 
OnCommand API Services를 처음 구축하는 경우
 a| 
* ONTAP 클러스터 9.6 이하가 있는 경우 OnCommand API 서비스 2.1 이상을 사용하고 있는 것입니다.
+
ONTAP 9.7 이상을 사용하는 경우 VASA Provider에 OnCommand API Services를 등록할 필요가 없습니다.

* NetApp Support 사이트에서 OnCommand API Services를 다운로드 및 설치한 후_OnCommand API 서비스 설치 및 설정 가이드에 제공된 설치 지침을 따라야 합니다.
* 각 VASA 공급자 인스턴스에는 전용 OnCommand API 서비스 인스턴스가 있어야 합니다.
+
OnCommand API 서비스는 여러 VASA 공급자 인스턴스 또는 vCenter Server 간에 공유해서는 안 됩니다.

* OnCommand API 서비스가 실행되고 있으며 액세스할 수 있습니다.




 a| 
수행할 수 있습니다
 a| 
* ONTAP 9.3 이상을 사용하고 있습니다.
* 스토리지 시스템에 적합한 자격 증명을 사용하고 있습니다.
* 스토리지 시스템이 활성 상태이며 액세스할 수 있습니다.
* 선택한 가상 머신에서 하나 이상의 VVol 데이터 저장소를 사용해야 하며, 가상 머신의 디스크에서 I/O 작업이 실행되고 있어야 합니다.


|===