---
permalink: manage/task_syslog_files.html 
sidebar: sidebar 
keywords:  
summary: Syslog는 시스템 로그를 중앙 집중식 로깅 서버로 보내는 데 사용됩니다. 
---
= syslog를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syslog를 사용하여 시스템 로그를 중앙 집중식 로깅 서버로 전송합니다.

* 이 작업에 대한 정보 *

ONTAP 툴은 VMware vSphere 9.12 이상용 ONTAP 툴을 통해 이전 2.0 syslog API를 제거합니다. 상호 인증을 지원하는 새로운 3.0 syslog 관련 API가 포함되어 있습니다.
syslog를 설정하려면 다음 단계를 따르십시오.

* 단계 *

. 세션 ID를 얻으려면 _POST/2.0/security/user/login을 실행하십시오.
. 위의 응답에서 받은 sessionid를 전달하여 _POST/3.0/appliance-management/logging-client-certificate_를 실행합니다.
+
그러면 VP 서버와 ONTAP 툴 서버에 대한 인증서가 생성됩니다.

. 두 인증서를 모두 syslog 서버에 복사하고 syslog 서버에서 신뢰할 수 있도록 합니다.
+
다음은 syslog-ng Docker에 대해 수행하는 방법에 대한 예입니다.

+
** JSON이 두 인증서를 모두 해제하고 PEM 형식의 인증서를 ca.d 디렉토리에 복사합니다
** `openssl x509 -noout -hash -in vsccert.pem` 결과는 해시입니다(예: 6d2962a8).
** `ln -s vsccert.pem 6d2962a8.0` 이렇게 하면 인증서에 대한 심볼 링크가 접미사가 .0인 해시로 생성됩니다
** syslog 서버를 시작합니다


. 서버 IP, 포트, 패턴(선택 사항), log_level 및 syslog 서버의 공용 인증서를 전달하여 _patch/3.0/appliance-management/syslog-config_API를 실행합니다.


로그는 지정된 syslog 서버로 라우팅됩니다.
